# Installs the approved emblem byte-for-byte and regenerates Android XML only.
# No raster editing, icon redesign, SDK, build, or external asset dependency.
[CmdletBinding()]
param([switch]$Check)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$res = Join-Path $root 'android/app/src/main/res'
$master = Join-Path $root 'assets/app/slovofon_icon.png'
$emblem = Join-Path $res 'drawable-nodpi/ic_launcher_emblem.png'

function Write-Resource([string]$relativePath, [string]$content) {
    $path = Join-Path $res $relativePath
    $content = $content.Replace("`r`n", "`n").TrimEnd() + "`n"
    if ($Check) {
        if (-not (Test-Path -LiteralPath $path) -or
            [IO.File]::ReadAllText($path).Replace("`r`n", "`n") -cne $content) {
            throw "Stale launcher resource: $relativePath"
        }
        return
    }
    New-Item -ItemType Directory -Force (Split-Path -Parent $path) | Out-Null
    [IO.File]::WriteAllText($path, $content, [Text.UTF8Encoding]::new($false))
}

if ($Check) {
    if (-not (Test-Path -LiteralPath $emblem) -or
        (Get-FileHash -LiteralPath $master).Hash -ne (Get-FileHash -LiteralPath $emblem).Hash) {
        throw 'The Android emblem must be the unchanged approved master PNG.'
    }
} else {
    New-Item -ItemType Directory -Force (Split-Path -Parent $emblem) | Out-Null
    Copy-Item -LiteralPath $master -Destination $emblem -Force
}

Write-Resource 'drawable/ic_launcher_background.xml' @'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by android/tools/Generate-LauncherAssets.ps1. Full-bleed navy. -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <size android:width="108dp" android:height="108dp" />
    <solid android:color="#071F32" />
</shape>
'@
Write-Resource 'drawable/ic_launcher_foreground.xml' @'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by android/tools/Generate-LauncherAssets.ps1.
     Keep the approved book/headphones/gold emblem unchanged, not the old SVG draft.
     Fractional insets scale with launcher bounds, unlike fixed-dp bitmap items.
     Original alpha bounds 92,81..1160,1166 in 1254 square give a 64.45 x 65.47 dp
     visible emblem on a 108 dp adaptive layer after 15% insets, inside 66 dp safe area.
     No monochrome disc: a full-colour bitmap is not a valid themed-icon silhouette. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <!-- Intrinsic layer is 108dp; fill scales it when Android changes the bounds. -->
    <item android:width="108dp" android:height="108dp" android:gravity="fill">
        <inset android:insetLeft="15%" android:insetTop="15%"
            android:insetRight="15%" android:insetBottom="15%">
            <bitmap android:src="@drawable/ic_launcher_emblem"
                android:gravity="fill" android:filter="true" />
        </inset>
    </item>
</layer-list>
'@
Write-Resource 'mipmap-anydpi-v26/ic_launcher.xml' @'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by android/tools/Generate-LauncherAssets.ps1.
     Android 8+ uses these layers instead of the white legacy-icon wrapper.
     API 24-25 keep the existing density-specific ic_launcher PNGs unchanged. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
'@

& (Join-Path $PSScriptRoot 'Generate-TvBanner.ps1') -Check:$Check
Write-Output $(if ($Check) { 'Android launcher assets are current.' } else { 'Android launcher assets regenerated.' })
