# Regenerates native vector banners from existing Slovofon book artwork and
# localized product names. Run on Windows; no SDK or build dependency is added.
# Text is stored as vector outlines, not as a redistributed font file.
[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$root = Split-Path -Parent $PSScriptRoot
$culture = [Globalization.CultureInfo]::InvariantCulture
function Number([single]$value) { $value.ToString('0.###', $culture) }
function Point($point) { (Number $point.X) + ',' + (Number $point.Y) }
function Wordmark([string]$name) {
    $font = [Drawing.FontFamily]::new('Segoe UI')
    $path = [Drawing.Drawing2D.GraphicsPath]::new()
    try {
        $path.AddString($name, $font, [int][Drawing.FontStyle]::Bold, 24, [Drawing.PointF]::new(0,0), [Drawing.StringFormat]::GenericTypographic)
        $bounds = $path.GetBounds()
        if ($bounds.Width -gt 166) {
            $scale = [Drawing.Drawing2D.Matrix]::new()
            try { $scale.Scale(166 / $bounds.Width, 166 / $bounds.Width); $path.Transform($scale) } finally { $scale.Dispose() }
            $bounds = $path.GetBounds()
        }
        $move = [Drawing.Drawing2D.Matrix]::new()
        try { $move.Translate(134 - $bounds.X, 90 - $bounds.Height / 2 - $bounds.Y); $path.Transform($move) } finally { $move.Dispose() }
        $points = $path.PathPoints
        $types = $path.PathTypes
        $result = [Text.StringBuilder]::new()
        for ($i = 0; $i -lt $points.Length; $i++) {
            switch ($types[$i] -band 7) {
                0 { [void]$result.Append('M' + (Point $points[$i])) }
                1 { [void]$result.Append('L' + (Point $points[$i])) }
                3 {
                    [void]$result.Append('C' + (Point $points[$i]) + ' ' + (Point $points[$i+1]) + ' ' + (Point $points[$i+2]))
                    $i += 2
                }
                default { throw 'Unexpected glyph outline segment' }
            }
            if (($types[$i] -band 128) -ne 0) { [void]$result.Append('Z') }
        }
        return $result.ToString()
    } finally { $path.Dispose(); $font.Dispose() }
}
foreach ($variant in @(@{Folder='drawable';Name='Slovofon'}, @{Folder='drawable-ru';Name='Словофон'})) {
    $wordmark = Wordmark $variant.Name
    $xml = @"
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by android/tools/Generate-TvBanner.ps1. Product name: $($variant.Name).
     Book paths are the existing assets/app/android_adaptive_icon_foreground.svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="320dp" android:height="180dp"
    android:viewportWidth="320" android:viewportHeight="180">
    <path android:fillColor="#172033" android:pathData="M0,0H320V180H0Z" />
    <group android:scaleX="0.35" android:scaleY="0.35"
        android:translateX="-11.4" android:translateY="12.4">
        <path android:fillColor="#F8FAFC" android:pathData="M84,132c54,-24 98,-18 132,12v170c-38,-28 -82,-36 -132,-12V132Z" />
        <path android:fillColor="#EAF0FF" android:pathData="M216,144c34,-30 78,-36 132,-12v170c-50,-24 -94,-16 -132,12V144Z" />
        <path android:strokeColor="#172033" android:strokeWidth="18"
            android:strokeLineCap="round" android:pathData="M260,276c22,-44 22,-78 0,-122" />
        <path android:strokeColor="#172033" android:strokeWidth="18"
            android:strokeLineCap="round" android:pathData="M306,304c36,-64 36,-122 0,-186" />
    </group>
    <path android:fillColor="#F8FAFC" android:pathData="$wordmark" />
</vector>
"@
    $directory = Join-Path $root "app/src/main/res/$($variant.Folder)"
    New-Item -ItemType Directory -Force $directory | Out-Null
    [IO.File]::WriteAllText((Join-Path $directory 'tv_banner.xml'), $xml + "`n", [Text.UTF8Encoding]::new($false))
}
