// GENERATED CODE - DO NOT MODIFY BY HAND.
// Source: assets/l10n/*.json. Regenerate: dart run tools/generate_localizations.dart
// dart format off
const appMessageCatalogs = <String, Map<String, String>>{
  "ru": {
    "aboutApp": "О приложении",
    "aboutAppHint": "Версия, сборка и ссылки проекта",
    "accentColor": "Акцентный цвет",
    "accentDefault": "По умолчанию",
    "accentGold": "Золотой",
    "accentGreen": "Зелёный",
    "accentRed": "Красный",
    "accentTeal": "Бирюзовый",
    "activeDownloads": "Активные",
    "addBookmark": "Добавить закладку",
    "addFavorite": "В избранное",
    "addToLater": "Отложить",
    "all": "Все",
    "allChapters": "Все главы",
    "allSources": "Все источники",
    "animations": "Анимации",
    "animationsFull": "Полные",
    "animationsOff": "Выключены",
    "animationsReduced": "Сниженные",
    "appTitle": "Словофон",
    "appUpdates": "Обновления",
    "appUpdatesHint": "Проверить новую версию",
    "appVersion": "Версия",
    "appearance": "Внешний вид",
    "apply": "Готово",
    "audioYearLabel": "Год озвучивания: {year}",
    "bookActions": "Действия с книгой",
    "bookDetails": "Карточка книги",
    "bookDetailsLoadFailedMessage": "Не получилось загрузить данные из источника «{sourceName}».",
    "bookDetailsLoadFailedTitle": "Не удалось открыть карточку книги",
    "bookFragment": "Ознакомительный фрагмент",
    "bookNotFoundMessage": "Источник «{sourceName}» не нашёл эту книгу. Возможно, страница была удалена.",
    "bookProgress": "Прогресс книги",
    "bookmarkAdded": "Закладка добавлена",
    "bookmarkNote": "Заметка",
    "bookmarkRemoved": "Закладка удалена",
    "bookmarkUnavailable": "Не удалось открыть книгу для этой закладки",
    "bookmarks": "Закладки",
    "booksCount.few": "{count} книги",
    "booksCount.many": "{count} книг",
    "booksCount.one": "{count} книга",
    "buildNumber": "Номер сборки",
    "byteUnit": "Б",
    "bytesPerSecond": "{bytes}/с",
    "cacheAndMetadata": "Кэш карточек",
    "cacheAndMetadataHint": "Обложки и сведения о книгах доступны без интернета и обновляются при открытии карточки.",
    "cacheClearFailed": "Не удалось очистить кэш. Попробуйте ещё раз.",
    "cacheCleared": "Кэш очищен: {books}, {size}",
    "cacheSize": "Размер: {value}",
    "calculatingTotalSize": "размер уточняется",
    "cancel": "Отменить",
    "cancelDownload": "Отменить загрузку",
    "cards": "Карточки",
    "chapterNumber": "Глава {number}",
    "chapterPosition": "Глава {current} из {total}",
    "chapters": "Главы",
    "chaptersCount.few": "{count} главы",
    "chaptersCount.many": "{count} глав",
    "chaptersCount.one": "{count} глава",
    "checkingUpdates": "Проверяю обновления...",
    "clearCacheSafetyHint": "Незавершённые загрузки также сохранятся.",
    "clearCardCache": "Очистить кэш карточек",
    "clearCardCacheConfirm": "Удалить обложки и сведения о книгах без скачанных файлов? Скачанные книги и главы, избранное, история и прогресс сохранятся.",
    "collapseChapters": "Свернуть главы",
    "colorBrightness": "Яркость",
    "colorHue": "Тон",
    "colorPreview": "Предпросмотр",
    "colorSaturation": "Насыщенность",
    "compactCards": "Компактные карточки",
    "completedDownloads": "Завершённые",
    "continueListening": "Продолжить прослушивание",
    "continuePlayback": "Продолжить",
    "currentAndNextChapters": "Текущая и следующие",
    "customColor": "Свой цвет",
    "dataAndDownloads": "Данные и загрузки",
    "deleteBookmark": "Удалить закладку?",
    "deleteBookmarkAction": "Удалить",
    "deleteBookmarkDescription": "Закладка будет удалена. Книга и прогресс прослушивания сохранятся.",
    "deleteDownloaded": "Удалить скачанное",
    "deleteSearchHistoryEntry": "Удалить из истории",
    "description": "Описание",
    "desktopLibraryLabel": "Аудиокниги",
    "details": "Подробнее",
    "diagnostics": "Диагностика",
    "diagnosticsHint": "Предпросмотр темы и безопасная проверка интерфейсных состояний.",
    "disableSleepTimer": "Отключить таймер",
    "disabled": "Выключено",
    "download": "Скачать",
    "downloadBook": "Скачать книгу",
    "downloadChaptersProgress.few": "{completed} из {total} глав",
    "downloadChaptersProgress.many": "{completed} из {total} глав",
    "downloadChaptersProgress.one": "{completed} из {total} главы",
    "downloadMetadataUnavailable": "Откройте книгу через поиск, чтобы восстановить её данные. Скачанные файлы сохранены.",
    "downloadMetadataUnavailableTitle": "Данные книги недоступны",
    "downloadQueuedMessage": "Книга добавлена в загрузки",
    "downloaded": "Скачанные",
    "downloadedBooksPreserved": "Скачанные книги не удаляются",
    "downloading": "Скачивается",
    "downloads": "Загрузки",
    "downloadsQueueSubtitle": "Очередь, прогресс, пауза, повтор и удаление оффлайн-файлов.",
    "downloadsSettingsHint": "Очередь, пауза, повтор и удаление оффлайн-файлов находятся на вкладке загрузок.",
    "emptyBookmarksShelf": "Нет закладок",
    "emptyBookmarksShelfMessage": "Добавьте закладку в плеере, чтобы вернуться к нужному моменту.",
    "emptyDownloadedShelf": "Нет скачанных книг",
    "emptyDownloadedShelfMessage": "Скачайте книгу, чтобы слушать без интернета.",
    "emptyDownloads": "Загрузок пока нет",
    "emptyDownloadsMessage": "Найдите книгу и скачайте её главы, чтобы слушать без интернета.",
    "emptyFavoritesShelf": "В избранном пока пусто",
    "emptyFavoritesShelfMessage": "Добавляйте понравившиеся книги с помощью сердца.",
    "emptyFinishedShelf": "Нет прослушанных книг",
    "emptyFinishedShelfMessage": "Здесь появятся книги, которые вы дослушали.",
    "emptyHistoryShelf": "История прослушивания пуста",
    "emptyHistoryShelfMessage": "Книги, которые вы запускали, будут показаны здесь.",
    "emptyLaterShelf": "Нет отложенных книг",
    "emptyLaterShelfMessage": "Выберите «Отложить» в меню книги, чтобы сохранить её на потом.",
    "emptyLibrary": "Библиотека пока пуста",
    "emptyListeningShelf": "Пока ничего не слушаете",
    "emptyListeningShelfMessage": "Начните слушать книгу — здесь появится ваш прогресс.",
    "enabled": "Включено",
    "enabledInSearch": "Используются в поиске",
    "failed": "Ошибка",
    "failedDownloads": "Ошибки",
    "favoriteAdded": "Добавлено в избранное",
    "favoriteRemoved": "Удалено из избранного",
    "favorites": "Избранное",
    "filter": "Фильтр",
    "filteredNoSearchResults": "Источник вернул данные, но после фильтра по полному запросу подходящих результатов нет.",
    "finished": "Прослушано",
    "forward15": "Вперёд на 15 секунд",
    "free": "Бесплатно",
    "fullPlayer": "Полный плеер",
    "genre": "Жанр",
    "gigabyteUnit": "ГБ",
    "githubRepository": "GitHub приложения",
    "goToCurrentChapter": "К текущей главе",
    "groupedDuplicates": "Группировать одинаковые",
    "hideDescription": "Скрыть описание",
    "history": "История",
    "home": "Главная",
    "homeDownloadsShortcutMessage": "Книги, которые можно слушать без интернета.",
    "homeLibraryShortcutMessage": "Избранные книги и сохранённые озвучки.",
    "hoursLabel": "{hours} ч",
    "hoursMinutesLabel": "{hours} ч {minutes} мин",
    "info": "Информация",
    "information": "Информация",
    "izibSearchSubtitle": "Реальная выдача источников, карточка и главы загружаются через SourceConnector.",
    "kilobyteUnit": "КБ",
    "language": "Язык",
    "later": "Позже",
    "library": "Библиотека",
    "libraryActionError": "Не удалось сохранить изменение",
    "libraryLoadError": "Не удалось загрузить библиотеку",
    "librarySourcesMessage": "Сохраняйте книги или начните слушать — они появятся здесь.",
    "listening": "Слушаю",
    "loading": "Загрузка...",
    "megabyteUnit": "МБ",
    "minutesLabel": "{minutes} мин",
    "mobileNavigationDownloads": "Загрузки",
    "mobileNavigationSettings": "Настройки",
    "mockDataNotice": "Каркас работает на локальных mock data. Источники будут подключены отдельным слоем.",
    "mute": "Без звука",
    "narratorUnknown": "Чтец не указан",
    "navigationTabLabel": "{label}\nВкладка {index} из {total}",
    "nextChapter": "Следующая глава",
    "nextTabs": "Следующие вкладки",
    "noBookmarks": "Нет закладок",
    "noInternetMessage": "Проверьте Wi-Fi или мобильную сеть и повторите попытку.",
    "noInternetTitle": "Нет соединения с интернетом",
    "noSearchResults": "Ничего не найдено",
    "noSearchResultsMessage": "Попробуйте другое название, автора или чтеца.",
    "noUpdatesAvailable": "Обновлений нет",
    "nowPlaying": "Сейчас играет",
    "offlineDownloads": "Скачанные для оффлайна",
    "openDownloads": "Открыть загрузки",
    "openFullPlayer": "Открыть полный плеер",
    "openPlayer": "Открыть плеер",
    "openSearch": "Открыть поиск",
    "openThemePreview": "Открыть предпросмотр темы",
    "otherNarrations": "Другие озвучки",
    "otherVersions": "Другие версии",
    "paid": "Платно",
    "partialSearchRetry": "Повторить поиск",
    "partialSearchSources": "Не ответили: {names}",
    "partialSourceFailures.few": "{count} источника вернули ошибку",
    "partialSourceFailures.many": "{count} источников вернули ошибку",
    "partialSourceFailures.one": "{count} источник вернул ошибку",
    "pause": "Пауза",
    "pauseDownload": "Поставить загрузку на паузу",
    "paused": "На паузе",
    "peopleAndOthers": "{names} и др.",
    "play": "Слушать",
    "playback": "Воспроизведение",
    "playbackSource": "Источник",
    "playbackSpeed": "Скорость воспроизведения",
    "player": "Плеер",
    "playerSettingsHint": "Скорость, таймер сна и управление главами находятся в полном плеере.",
    "previewButtons": "Кнопки",
    "previewCards": "Карточки",
    "previewChips": "Чипы",
    "previewInputs": "Поля ввода",
    "previewStates": "Состояния",
    "previousChapter": "Предыдущая глава",
    "previousTabs": "Предыдущие вкладки",
    "projectWebsite": "Сайт проекта",
    "proxy": "Прокси",
    "queued": "В очереди",
    "queuedDownloads": "Очередь",
    "ratingOutOfFive": "{rating} из 5",
    "realSourceHomeMessage": "Поиск, карточки, главы, плеер и загрузки подключены к реальным источникам Izib, Akniga, Yakniga, Knigavuhe, Knigoblud и Baza Knig.",
    "realSourceHomeTitle": "Найдите книгу",
    "recentSearches": "История поиска",
    "recommended": "Рекомендации на mock data",
    "removeFavorite": "Убрать из избранного",
    "removeFromLater": "Убрать из «Позже»",
    "resume": "Продолжить",
    "resumeDownload": "Продолжить загрузку",
    "retry": "Повторить",
    "rewind15": "Назад на 15 секунд",
    "saveBookmark": "Сохранить закладку",
    "savedBookMediaUnavailable": "Нет сохранённых аудиоглав. Найдите книгу в источнике.",
    "savedBookNotFound": "Книга не найдена в библиотеке",
    "savedBookPlaybackError": "Не удалось начать воспроизведение",
    "search": "Поиск",
    "searchByAuthor": "Автор",
    "searchByGenre": "Жанр",
    "searchByNarrator": "Чтец",
    "searchBySeries": "Цикл",
    "searchByTitle": "Название",
    "searchHint": "Название, автор, чтец, цикл или жанр",
    "searchHistoryEmptyMessage": "Здесь появятся ваши недавние запросы — их можно повторить или удалить.",
    "searchReadyMessage": "Поиск подключён к реальным источникам Izib, Akniga, Yakniga, Knigavuhe, Knigoblud и Baza Knig.",
    "searchReadyTitle": "Введите запрос",
    "searchResults": "Результаты",
    "searchScope": "Искать по",
    "searchShortQueryMessage": "Введите минимум 2 символа.",
    "searchShortQueryTitle": "Слишком короткий запрос",
    "searchingSources": "Ищу в источниках...",
    "selectAtLeastOneSearchKind": "Выберите хотя бы одно поле поиска.",
    "selectAtLeastOneSource": "Выберите хотя бы один источник",
    "selectedSourcesCount.few": "{count} источника включены",
    "selectedSourcesCount.many": "{count} источников включено",
    "selectedSourcesCount.one": "{count} источник включён",
    "series": "Цикл",
    "settings": "Настройки",
    "settingsApplication": "Приложение",
    "settingsContent": "Контент и хранение",
    "settingsPersonalization": "Персонализация",
    "settingsSections": "Разделы настроек",
    "share": "Поделиться",
    "shareLinkCopied": "Ссылка скопирована",
    "shareSlovofonLink": "Ссылка Словофон",
    "shareSourceLink": "Ссылка источника",
    "showFullDescription": "Показать полностью",
    "showMoreChapters.few": "Показать ещё {count} главы",
    "showMoreChapters.many": "Показать ещё {count} глав",
    "showMoreChapters.one": "Показать ещё {count} главу",
    "showPercentOnCovers": "Процент прослушивания на обложках",
    "showSourceOnCards": "Название источника на карточках",
    "skipUpdate": "Пропустить версию",
    "sleepTimer": "Таймер сна",
    "sleepTimerUntilChapterEnd": "До конца главы",
    "snackbarPreview": "Snackbar",
    "sort": "Сортировка",
    "sortByDuration": "длительность",
    "sortByRating": "рейтинг",
    "sortByRelevance": "релевантность",
    "sortByTitle": "название",
    "sortByYear": "год",
    "sourceDisplayName.akniga": "Akniga",
    "sourceDisplayName.bazaKnig": "База книг",
    "sourceDisplayName.izib": "Изибук",
    "sourceDisplayName.knigavuhe": "Книга в ухе",
    "sourceDisplayName.knigoblud": "Книгоблуд",
    "sourceDisplayName.yakniga": "Yakniga",
    "sourceDownloadDisabled": "Загрузка из этого источника отключена в настройках",
    "sourceFilter": "Источники",
    "sourcePage": "Страница на сайте источника",
    "sourcePageOpenError": "Не удалось открыть страницу источника",
    "sourceResultsCount.few": "{count} результата",
    "sourceResultsCount.many": "{count} результатов",
    "sourceResultsCount.one": "{count} результат",
    "sourceSearchDisabled": "Исключён из поиска",
    "sourceSearchEnabled": "Включён в поиск",
    "sourceSearchError": "Не удалось выполнить поиск",
    "sourceStats": "Статистика источника",
    "sourceStreamingDisabled": "Воспроизведение из этого источника отключено в настройках",
    "sourceUnavailableMessage": "Повторите попытку позже или проверьте соединение.",
    "sourceUnavailableTitle": "Источник «{sourceName}» недоступен",
    "sources": "Источники",
    "startedBooks": "Начатые книги",
    "subscription": "Подписка",
    "success": "Успешно",
    "systemLanguage": "Язык системы",
    "telegramChannel": "Telegram-канал",
    "telegramChat": "Telegram-чат",
    "telegramSupportBot": "Telegram-бот поддержки",
    "terabyteUnit": "ТБ",
    "textSize": "Размер текста",
    "textSizeHint": "100% — системный размер текста. Изменения применяются после отпускания ползунка.",
    "textSizeLabel": "Размер текста: {percent}%",
    "textSizePreview": "Так будет выглядеть текст в приложении.",
    "textSizeReset": "Вернуть 100%",
    "theme": "Тема",
    "themeAmoled": "AMOLED",
    "themeDark": "Тёмная",
    "themeLight": "Светлая",
    "themeModeLabel": "Тема: {value}",
    "themePreview": "Предпросмотр темы",
    "themeSystem": "Системная",
    "unknown": "Неизвестно",
    "unknownSize": "Размер неизвестен",
    "updateAvailableMessage": "Доступна версия {version}. Размер обновления: {size}.",
    "updateAvailableTitle": "Доступно обновление",
    "updateChannel": "Канал обновлений",
    "updateCheckFailed": "Не удалось проверить обновления",
    "updateCheckFailedMessage": "Проверьте соединение и нажмите «Повторить».",
    "updateDownloadFailed": "Не удалось скачать обновление",
    "updateDownloadFailedMessage": "Проверьте соединение и нажмите «Повторить».",
    "updateDownloadProgress": "{downloaded} из {total} · {speed}/с",
    "updateDownloadZip": "Скачать ZIP",
    "updateDownloading": "Скачиваю обновление...",
    "updateInstallFailed": "Не удалось запустить обновление",
    "updateInstallFailedMessage": "Не удалось подготовить или открыть файл обновления. Проверьте разрешения системы и нажмите «Повторить». Приложение не будет закрыто автоматически.",
    "updateInstallPermissionRequired": "Разрешите установку APK для Словофона и нажмите «Обновить» ещё раз.",
    "updateInstallerHint": "После проверки файла откроется установщик. Следуйте его инструкциям; настройки, прогресс и скачанные книги сохраняются.",
    "updateInstallerStarted": "Установщик обновления открыт",
    "updateLater": "Позже",
    "updateManualDownloadHint": "Не удалось надёжно определить тип установки Windows. Выберите подходящий файл на странице релизов; приложение не будет заменено автоматически.",
    "updateNotesAlert.caution": "Внимание",
    "updateNotesAlert.important": "Важно",
    "updateNotesAlert.note": "Примечание",
    "updateNotesAlert.tip": "Совет",
    "updateNotesAlert.warning": "Предупреждение",
    "updateNotesLinkFailed": "Не удалось открыть ссылку. Проверьте, установлен ли браузер.",
    "updateNotesRemoteHint": "Вверх и вниз — прокрутка. Вправо — переход к ссылкам.",
    "updateNotesTruncated": "Показана часть описания. Полный текст доступен на странице релиза.",
    "updateNow": "Обновить",
    "updateOpenReleases": "Открыть страницу релизов",
    "updatePortableHint": "Будет скачан и проверен ZIP-архив. Затем закройте Словофон и распакуйте архив в новую папку. Не удаляйте папки с пользовательскими данными и скачанными книгами.",
    "updatePortableReady": "Архив проверен; открыта папка загрузки. Закройте Словофон и распакуйте ZIP в новую папку.",
    "updatePreparingTitle": "Проверка и запуск обновления",
    "updateReleaseNotes": "Что нового",
    "updateReleasePageFailed": "Не удалось открыть страницу релизов. Повторите попытку.",
    "updateSkipFailed": "Не удалось сохранить пропуск версии. Повторите попытку или нажмите «Позже».",
    "updateUnsupportedPlatform": "Для этой платформы нет подходящего файла обновления",
    "volume": "Громкость",
    "warning": "Внимание",
  },
  "en": {
    "aboutApp": "About",
    "aboutAppHint": "Version, build, and links",
    "accentColor": "Accent color",
    "accentDefault": "Default",
    "accentGold": "Gold",
    "accentGreen": "Green",
    "accentRed": "Red",
    "accentTeal": "Teal",
    "activeDownloads": "Active",
    "addBookmark": "Add bookmark",
    "addFavorite": "Add to favorites",
    "addToLater": "Listen later",
    "all": "All",
    "allChapters": "All chapters",
    "allSources": "All sources",
    "animations": "Animations",
    "animationsFull": "Full",
    "animationsOff": "Off",
    "animationsReduced": "Reduced",
    "appTitle": "Slovofon",
    "appUpdates": "Updates",
    "appUpdatesHint": "Check for a new version",
    "appVersion": "Version",
    "appearance": "Appearance",
    "apply": "Done",
    "audioYearLabel": "Audio year: {year}",
    "bookActions": "Book actions",
    "bookDetails": "Book details",
    "bookDetailsLoadFailedMessage": "Could not load data from {sourceName}.",
    "bookDetailsLoadFailedTitle": "Could not open book details",
    "bookFragment": "Sample",
    "bookNotFoundMessage": "{sourceName} did not find this book. The page may have been removed.",
    "bookProgress": "Book progress",
    "bookmarkAdded": "Bookmark added",
    "bookmarkNote": "Note",
    "bookmarkRemoved": "Bookmark removed",
    "bookmarkUnavailable": "Could not open the book for this bookmark",
    "bookmarks": "Bookmarks",
    "booksCount.few": "{count} books",
    "booksCount.many": "{count} books",
    "booksCount.one": "{count} book",
    "buildNumber": "Build number",
    "byteUnit": "B",
    "bytesPerSecond": "{bytes}/s",
    "cacheAndMetadata": "Card cache",
    "cacheAndMetadataHint": "Covers and book details are available offline and refresh when you open a book.",
    "cacheClearFailed": "Could not clear the cache. Please try again.",
    "cacheCleared": "Cache cleared: {books}, {size}",
    "cacheSize": "Size: {value}",
    "calculatingTotalSize": "size is being calculated",
    "cancel": "Cancel",
    "cancelDownload": "Cancel download",
    "cards": "Cards",
    "chapterNumber": "Chapter {number}",
    "chapterPosition": "Chapter {current} of {total}",
    "chapters": "Chapters",
    "chaptersCount.few": "{count} chapters",
    "chaptersCount.many": "{count} chapters",
    "chaptersCount.one": "{count} chapter",
    "checkingUpdates": "Checking for updates...",
    "clearCacheSafetyHint": "Partial downloads will also be kept.",
    "clearCardCache": "Clear card cache",
    "clearCardCacheConfirm": "Remove covers and details for books without downloaded files? Downloaded books and chapters, favorites, history, and progress will be kept.",
    "collapseChapters": "Collapse chapters",
    "colorBrightness": "Brightness",
    "colorHue": "Hue",
    "colorPreview": "Preview",
    "colorSaturation": "Saturation",
    "compactCards": "Compact cards",
    "completedDownloads": "Completed",
    "continueListening": "Continue listening",
    "continuePlayback": "Continue",
    "currentAndNextChapters": "Current and next",
    "customColor": "Custom color",
    "dataAndDownloads": "Data and downloads",
    "deleteBookmark": "Delete bookmark?",
    "deleteBookmarkAction": "Delete",
    "deleteBookmarkDescription": "The bookmark will be removed. The book and listening progress will be kept.",
    "deleteDownloaded": "Delete downloaded",
    "deleteSearchHistoryEntry": "Delete from history",
    "description": "Description",
    "desktopLibraryLabel": "Audiobooks",
    "details": "Details",
    "diagnostics": "Diagnostics",
    "diagnosticsHint": "Theme preview and safe UI state checks.",
    "disableSleepTimer": "Disable timer",
    "disabled": "Disabled",
    "download": "Download",
    "downloadBook": "Download book",
    "downloadChaptersProgress.few": "{completed} of {total} chapters",
    "downloadChaptersProgress.many": "{completed} of {total} chapters",
    "downloadChaptersProgress.one": "{completed} of {total} chapter",
    "downloadMetadataUnavailable": "Open the book from search to restore its details. Downloaded files are preserved.",
    "downloadMetadataUnavailableTitle": "Book details unavailable",
    "downloadQueuedMessage": "Book added to downloads",
    "downloaded": "Downloaded",
    "downloadedBooksPreserved": "Downloaded books are preserved",
    "downloading": "Downloading",
    "downloads": "Downloads",
    "downloadsQueueSubtitle": "Queue, progress, pause, retry, and offline file removal.",
    "downloadsSettingsHint": "Queue, pause, retry, and offline file removal live on the downloads tab.",
    "emptyBookmarksShelf": "No bookmarks",
    "emptyBookmarksShelfMessage": "Add a bookmark in the player to return to a specific moment.",
    "emptyDownloadedShelf": "No downloaded books",
    "emptyDownloadedShelfMessage": "Download a book to listen offline.",
    "emptyDownloads": "No downloads yet",
    "emptyDownloadsMessage": "Find a book and download its chapters to listen offline.",
    "emptyFavoritesShelf": "No favorites yet",
    "emptyFavoritesShelfMessage": "Use the heart button to add books you like.",
    "emptyFinishedShelf": "No finished books",
    "emptyFinishedShelfMessage": "Books you finish listening to will appear here.",
    "emptyHistoryShelf": "Listening history is empty",
    "emptyHistoryShelfMessage": "Books you have played will appear here.",
    "emptyLaterShelf": "No books saved for later",
    "emptyLaterShelfMessage": "Choose Listen later in a book’s menu to save it for later.",
    "emptyLibrary": "Your library is empty",
    "emptyListeningShelf": "No books in progress",
    "emptyListeningShelfMessage": "Start listening to a book to see your progress here.",
    "enabled": "Enabled",
    "enabledInSearch": "Enabled in search",
    "failed": "Failed",
    "failedDownloads": "Errors",
    "favoriteAdded": "Added to favorites",
    "favoriteRemoved": "Removed from favorites",
    "favorites": "Favorites",
    "filter": "Filter",
    "filteredNoSearchResults": "The source returned data, but none matched every query word.",
    "finished": "Finished",
    "forward15": "Forward 15 seconds",
    "free": "Free",
    "fullPlayer": "Full player",
    "genre": "Genre",
    "gigabyteUnit": "GB",
    "githubRepository": "Application GitHub",
    "goToCurrentChapter": "Current chapter",
    "groupedDuplicates": "Grouped duplicates",
    "hideDescription": "Hide description",
    "history": "History",
    "home": "Home",
    "homeDownloadsShortcutMessage": "Books you can listen to offline.",
    "homeLibraryShortcutMessage": "Favorite books and saved narrations.",
    "hoursLabel": "{hours} h",
    "hoursMinutesLabel": "{hours} h {minutes} min",
    "info": "Info",
    "information": "Information",
    "izibSearchSubtitle": "Real source results; details and chapters are loaded through SourceConnector.",
    "kilobyteUnit": "KB",
    "language": "Language",
    "later": "Later",
    "library": "Library",
    "libraryActionError": "Could not save the change",
    "libraryLoadError": "Could not load the library",
    "librarySourcesMessage": "Save books or start listening to see them here.",
    "listening": "Listening",
    "loading": "Loading...",
    "megabyteUnit": "MB",
    "minutesLabel": "{minutes} min",
    "mobileNavigationDownloads": "Downloads",
    "mobileNavigationSettings": "Settings",
    "mockDataNotice": "This scaffold uses local mock data. Sources will be wired through a separate layer.",
    "mute": "Mute",
    "narratorUnknown": "Narrator not specified",
    "navigationTabLabel": "{label}\nTab {index} of {total}",
    "nextChapter": "Next chapter",
    "nextTabs": "Next tabs",
    "noBookmarks": "No bookmarks",
    "noInternetMessage": "Check Wi-Fi or mobile data and try again.",
    "noInternetTitle": "No internet connection",
    "noSearchResults": "No results",
    "noSearchResultsMessage": "Try another title, author, or narrator.",
    "noUpdatesAvailable": "No updates available",
    "nowPlaying": "Now playing",
    "offlineDownloads": "Offline downloads",
    "openDownloads": "Open downloads",
    "openFullPlayer": "Open full player",
    "openPlayer": "Open player",
    "openSearch": "Open search",
    "openThemePreview": "Open theme preview",
    "otherNarrations": "Other narrations",
    "otherVersions": "Other versions",
    "paid": "Paid",
    "partialSearchRetry": "Retry search",
    "partialSearchSources": "Unavailable: {names}",
    "partialSourceFailures.few": "{count} source failures",
    "partialSourceFailures.many": "{count} source failures",
    "partialSourceFailures.one": "{count} source failure",
    "pause": "Pause",
    "pauseDownload": "Pause download",
    "paused": "Paused",
    "peopleAndOthers": "{names} et al.",
    "play": "Play",
    "playback": "Playback",
    "playbackSource": "Source",
    "playbackSpeed": "Playback speed",
    "player": "Player",
    "playerSettingsHint": "Speed, sleep timer, and chapter controls live in the full player.",
    "previewButtons": "Buttons",
    "previewCards": "Cards",
    "previewChips": "Chips",
    "previewInputs": "Inputs",
    "previewStates": "States",
    "previousChapter": "Previous chapter",
    "previousTabs": "Previous tabs",
    "projectWebsite": "Project website",
    "proxy": "Proxy",
    "queued": "Queued",
    "queuedDownloads": "Queued",
    "ratingOutOfFive": "{rating} out of 5",
    "realSourceHomeMessage": "Search, cards, chapters, playback, and downloads are connected to Izib, Akniga, Yakniga, Knigavuhe, Knigoblud, and Baza Knig.",
    "realSourceHomeTitle": "Find a book",
    "recentSearches": "Recent searches",
    "recommended": "Mock recommendations",
    "removeFavorite": "Remove from favorites",
    "removeFromLater": "Remove from listen later",
    "resume": "Resume",
    "resumeDownload": "Resume download",
    "retry": "Retry",
    "rewind15": "Rewind 15 seconds",
    "saveBookmark": "Save bookmark",
    "savedBookMediaUnavailable": "No saved audio chapters. Find the book in a source.",
    "savedBookNotFound": "Book not found in the library",
    "savedBookPlaybackError": "Could not start playback",
    "search": "Search",
    "searchByAuthor": "Author",
    "searchByGenre": "Genre",
    "searchByNarrator": "Narrator",
    "searchBySeries": "Series",
    "searchByTitle": "Title",
    "searchHint": "Title, author, narrator, series, or genre",
    "searchHistoryEmptyMessage": "Your recent searches will appear here so you can repeat or delete them.",
    "searchReadyMessage": "Search is connected to Izib, Akniga, Yakniga, Knigavuhe, Knigoblud, and Baza Knig.",
    "searchReadyTitle": "Enter a search query",
    "searchResults": "Results",
    "searchScope": "Search in",
    "searchShortQueryMessage": "Enter at least 2 characters.",
    "searchShortQueryTitle": "Query is too short",
    "searchingSources": "Searching sources...",
    "selectAtLeastOneSearchKind": "Select at least one search field.",
    "selectAtLeastOneSource": "Select at least one source",
    "selectedSourcesCount.few": "{count} sources enabled",
    "selectedSourcesCount.many": "{count} sources enabled",
    "selectedSourcesCount.one": "{count} source enabled",
    "series": "Series",
    "settings": "Settings",
    "settingsApplication": "Application",
    "settingsContent": "Content and storage",
    "settingsPersonalization": "Personalization",
    "settingsSections": "Settings sections",
    "share": "Share",
    "shareLinkCopied": "Link copied",
    "shareSlovofonLink": "Slovofon link",
    "shareSourceLink": "Source link",
    "showFullDescription": "Show full description",
    "showMoreChapters.few": "Show {count} more chapters",
    "showMoreChapters.many": "Show {count} more chapters",
    "showMoreChapters.one": "Show {count} more chapter",
    "showPercentOnCovers": "Progress percent on covers",
    "showSourceOnCards": "Source name on cards",
    "skipUpdate": "Skip this version",
    "sleepTimer": "Sleep timer",
    "sleepTimerUntilChapterEnd": "Until chapter ends",
    "snackbarPreview": "Snackbar",
    "sort": "Sort",
    "sortByDuration": "duration",
    "sortByRating": "rating",
    "sortByRelevance": "relevance",
    "sortByTitle": "title",
    "sortByYear": "year",
    "sourceDisplayName.akniga": "Akniga",
    "sourceDisplayName.bazaKnig": "Baza Knig",
    "sourceDisplayName.izib": "Izib",
    "sourceDisplayName.knigavuhe": "Knigavuhe",
    "sourceDisplayName.knigoblud": "Knigoblud",
    "sourceDisplayName.yakniga": "Yakniga",
    "sourceDownloadDisabled": "Downloads from this source are disabled in settings",
    "sourceFilter": "Sources",
    "sourcePage": "Source page",
    "sourcePageOpenError": "Could not open source page",
    "sourceResultsCount.few": "{count} results",
    "sourceResultsCount.many": "{count} results",
    "sourceResultsCount.one": "{count} result",
    "sourceSearchDisabled": "Excluded from search",
    "sourceSearchEnabled": "Included in search",
    "sourceSearchError": "Search failed",
    "sourceStats": "Source stats",
    "sourceStreamingDisabled": "Streaming from this source is disabled in settings",
    "sourceUnavailableMessage": "Try again later or check your connection.",
    "sourceUnavailableTitle": "{sourceName} is unavailable",
    "sources": "Sources",
    "startedBooks": "Started books",
    "subscription": "Subscription",
    "success": "Success",
    "systemLanguage": "System language",
    "telegramChannel": "Telegram channel",
    "telegramChat": "Telegram chat",
    "telegramSupportBot": "Telegram support bot",
    "terabyteUnit": "TB",
    "textSize": "Text size",
    "textSizeHint": "100% follows the system text size. Changes apply when you release the slider.",
    "textSizeLabel": "Text size: {percent}%",
    "textSizePreview": "This is how text will look in the app.",
    "textSizeReset": "Reset to 100%",
    "theme": "Theme",
    "themeAmoled": "AMOLED",
    "themeDark": "Dark",
    "themeLight": "Light",
    "themeModeLabel": "Theme: {value}",
    "themePreview": "Theme preview",
    "themeSystem": "System",
    "unknown": "Unknown",
    "unknownSize": "Unknown size",
    "updateAvailableMessage": "Version {version} is available. Update size: {size}.",
    "updateAvailableTitle": "Update available",
    "updateChannel": "Update channel",
    "updateCheckFailed": "Update check failed",
    "updateCheckFailedMessage": "Check your connection and tap Retry.",
    "updateDownloadFailed": "Update download failed",
    "updateDownloadFailedMessage": "Check your connection and tap Retry.",
    "updateDownloadProgress": "{downloaded} of {total} · {speed}/s",
    "updateDownloadZip": "Download ZIP",
    "updateDownloading": "Downloading update...",
    "updateInstallFailed": "Could not start the update",
    "updateInstallFailedMessage": "The update file could not be prepared or opened. Check system permissions and choose Retry. The app will not close automatically.",
    "updateInstallPermissionRequired": "Allow APK installs for Slovofon, then tap Update again.",
    "updateInstallerHint": "After the file is verified, the installer will open. Follow its instructions; settings, progress and downloaded books are preserved.",
    "updateInstallerStarted": "The update installer has been opened",
    "updateLater": "Later",
    "updateManualDownloadHint": "The Windows installation type could not be determined reliably. Choose the matching file on the releases page; this app will not be replaced automatically.",
    "updateNotesAlert.caution": "Caution",
    "updateNotesAlert.important": "Important",
    "updateNotesAlert.note": "Note",
    "updateNotesAlert.tip": "Tip",
    "updateNotesAlert.warning": "Warning",
    "updateNotesLinkFailed": "Could not open the link. Check that a browser is installed.",
    "updateNotesRemoteHint": "Up and down to scroll. Right to focus links.",
    "updateNotesTruncated": "Part of the description is shown. Read the full text on the release page.",
    "updateNow": "Update",
    "updateOpenReleases": "Open releases page",
    "updatePortableHint": "The ZIP archive will be downloaded and verified. Then close Slovofon and extract it into a new folder. Keep your user-data and downloaded-book folders.",
    "updatePortableReady": "The archive is verified and its folder is open. Close Slovofon and extract the ZIP into a new folder.",
    "updatePreparingTitle": "Verifying and starting update",
    "updateReleaseNotes": "What is new",
    "updateReleasePageFailed": "Could not open the releases page. Try again.",
    "updateSkipFailed": "Could not save the skipped version. Try again or choose Later.",
    "updateUnsupportedPlatform": "No suitable update file is available for this platform",
    "volume": "Volume",
    "warning": "Warning",
  },
  "kk": {
    "aboutApp": "Қолданба туралы",
    "aboutAppHint": "Нұсқа, жинақ және жоба сілтемелері",
    "accentColor": "Акцент түсі",
    "accentDefault": "Әдепкі",
    "accentGold": "Алтын түсті",
    "accentGreen": "Жасыл",
    "accentRed": "Қызыл",
    "accentTeal": "Көкшіл жасыл",
    "activeDownloads": "Белсенді",
    "addBookmark": "Бетбелгі қосу",
    "addFavorite": "Таңдаулыларға қосу",
    "addToLater": "Кейін тыңдау",
    "all": "Барлығы",
    "allChapters": "Барлық тараулар",
    "allSources": "Барлық дереккөздер",
    "animations": "Анимациялар",
    "animationsFull": "Толық",
    "animationsOff": "Өшірулі",
    "animationsReduced": "Азайтылған",
    "appTitle": "Slovofon",
    "appUpdates": "Жаңартулар",
    "appUpdatesHint": "Жаңа нұсқаны тексеру",
    "appVersion": "Нұсқа",
    "appearance": "Сыртқы көрініс",
    "apply": "Дайын",
    "audioYearLabel": "Дыбысталған жыл: {year}",
    "bookActions": "Кітаппен әрекеттер",
    "bookDetails": "Кітап карточкасы",
    "bookDetailsLoadFailedMessage": "«{sourceName}» дереккөзінен мәліметтерді жүктеу мүмкін болмады.",
    "bookDetailsLoadFailedTitle": "Кітап карточкасын ашу мүмкін болмады",
    "bookFragment": "Танысу үзіндісі",
    "bookNotFoundMessage": "«{sourceName}» дереккөзі бұл кітапты таппады. Бет жойылған болуы мүмкін.",
    "bookProgress": "Кітаптың тыңдалу барысы",
    "bookmarkAdded": "Бетбелгі қосылды",
    "bookmarkNote": "Жазба",
    "bookmarkRemoved": "Бетбелгі жойылды",
    "bookmarkUnavailable": "Бұл бетбелгінің кітабын ашу мүмкін болмады",
    "bookmarks": "Бетбелгілер",
    "booksCount.few": "{count} кітап",
    "booksCount.many": "{count} кітап",
    "booksCount.one": "{count} кітап",
    "buildNumber": "Жинақ нөмірі",
    "byteUnit": "Б",
    "bytesPerSecond": "{bytes}/с",
    "cacheAndMetadata": "Карточкалар кэші",
    "cacheAndMetadataHint": "Мұқабалар мен кітап мәліметтері интернетсіз қолжетімді және карточканы ашқанда жаңартылады.",
    "cacheClearFailed": "Кэшті тазалау мүмкін болмады. Қайталап көріңіз.",
    "cacheCleared": "Кэш тазаланды: {books}, {size}",
    "cacheSize": "Көлемі: {value}",
    "calculatingTotalSize": "көлемі есептелуде",
    "cancel": "Бас тарту",
    "cancelDownload": "Жүктеуден бас тарту",
    "cards": "Карточкалар",
    "chapterNumber": "{number}-тарау",
    "chapterPosition": "Тарау {current} / {total}",
    "chapters": "Тараулар",
    "chaptersCount.few": "{count} тарау",
    "chaptersCount.many": "{count} тарау",
    "chaptersCount.one": "{count} тарау",
    "checkingUpdates": "Жаңартулар тексерілуде...",
    "clearCacheSafetyHint": "Аяқталмаған жүктеулер де сақталады.",
    "clearCardCache": "Карточкалар кэшін тазалау",
    "clearCardCacheConfirm": "Жүктелген файлдары жоқ кітаптардың мұқабалары мен мәліметтерін жою керек пе? Жүктелген кітаптар мен тараулар, таңдаулылар, тарих және тыңдалу барысы сақталады.",
    "collapseChapters": "Тарауларды жию",
    "colorBrightness": "Жарықтық",
    "colorHue": "Реңк",
    "colorPreview": "Алдын ала қарау",
    "colorSaturation": "Қанықтық",
    "compactCards": "Ықшам карточкалар",
    "completedDownloads": "Аяқталған",
    "continueListening": "Тыңдауды жалғастыру",
    "continuePlayback": "Жалғастыру",
    "currentAndNextChapters": "Ағымдағы және келесі",
    "customColor": "Өз түсіңіз",
    "dataAndDownloads": "Деректер және жүктеулер",
    "deleteBookmark": "Бетбелгіні жою керек пе?",
    "deleteBookmarkAction": "Жою",
    "deleteBookmarkDescription": "Бетбелгі жойылады. Кітап пен тыңдалу барысы сақталады.",
    "deleteDownloaded": "Жүктелгендерді жою",
    "deleteSearchHistoryEntry": "Тарихтан жою",
    "description": "Сипаттама",
    "desktopLibraryLabel": "Аудиокітаптар",
    "details": "Толығырақ",
    "diagnostics": "Диагностика",
    "diagnosticsHint": "Тақырыпты алдын ала қарау және интерфейс күйлерін қауіпсіз тексеру.",
    "disableSleepTimer": "Таймерді өшіру",
    "disabled": "Өшірулі",
    "download": "Жүктеп алу",
    "downloadBook": "Кітапты жүктеп алу",
    "downloadChaptersProgress.few": "{total} тараудың {completed} тарауы",
    "downloadChaptersProgress.many": "{total} тараудың {completed} тарауы",
    "downloadChaptersProgress.one": "{total} тараудың {completed} тарауы",
    "downloadMetadataUnavailable": "Мәліметтерін қалпына келтіру үшін кітапты іздеу арқылы ашыңыз. Жүктелген файлдар сақталған.",
    "downloadMetadataUnavailableTitle": "Кітап мәліметтері қолжетімсіз",
    "downloadQueuedMessage": "Кітап жүктеулерге қосылды",
    "downloaded": "Жүктелген",
    "downloadedBooksPreserved": "Жүктелген кітаптар жойылмайды",
    "downloading": "Жүктелуде",
    "downloads": "Жүктеулер",
    "downloadsQueueSubtitle": "Кезек, жүктелу барысы, кідірту, қайталау және офлайн файлдарды жою.",
    "downloadsSettingsHint": "Кезек, кідірту, қайталау және офлайн файлдарды жою жүктеулер қойындысында орналасқан.",
    "emptyBookmarksShelf": "Бетбелгілер жоқ",
    "emptyBookmarksShelfMessage": "Қажетті сәтке оралу үшін ойнатқышта бетбелгі қосыңыз.",
    "emptyDownloadedShelf": "Жүктелген кітаптар жоқ",
    "emptyDownloadedShelfMessage": "Интернетсіз тыңдау үшін кітапты жүктеп алыңыз.",
    "emptyDownloads": "Жүктеулер әзірге жоқ",
    "emptyDownloadsMessage": "Интернетсіз тыңдау үшін кітапты тауып, тарауларын жүктеп алыңыз.",
    "emptyFavoritesShelf": "Таңдаулылар әзірге бос",
    "emptyFavoritesShelfMessage": "Ұнаған кітаптарды жүрек батырмасымен қосыңыз.",
    "emptyFinishedShelf": "Тыңдалып біткен кітаптар жоқ",
    "emptyFinishedShelfMessage": "Тыңдап бітірген кітаптарыңыз осында пайда болады.",
    "emptyHistoryShelf": "Тыңдау тарихы бос",
    "emptyHistoryShelfMessage": "Сіз қосқан кітаптар осында көрсетіледі.",
    "emptyLaterShelf": "Кейінге сақталған кітаптар жоқ",
    "emptyLaterShelfMessage": "Кітапты кейінге сақтау үшін оның мәзірінен «Кейін тыңдау» пәрменін таңдаңыз.",
    "emptyLibrary": "Кітапхана әзірге бос",
    "emptyListeningShelf": "Әзірге ештеңе тыңдап жатқан жоқсыз",
    "emptyListeningShelfMessage": "Кітап тыңдауды бастаңыз — тыңдалу барысы осында көрсетіледі.",
    "enabled": "Қосулы",
    "enabledInSearch": "Іздеуде қолданылады",
    "failed": "Қате",
    "failedDownloads": "Қателер",
    "favoriteAdded": "Таңдаулыларға қосылды",
    "favoriteRemoved": "Таңдаулылардан алынды",
    "favorites": "Таңдаулылар",
    "filter": "Сүзгі",
    "filteredNoSearchResults": "Дереккөз мәліметтер қайтарды, бірақ сұраудың барлық сөзіне сай нәтиже жоқ.",
    "finished": "Тыңдалып біткен",
    "forward15": "15 секунд алға",
    "free": "Тегін",
    "fullPlayer": "Толық ойнатқыш",
    "genre": "Жанр",
    "gigabyteUnit": "ГБ",
    "githubRepository": "Қолданбаның GitHub парақшасы",
    "goToCurrentChapter": "Ағымдағы тарауға",
    "groupedDuplicates": "Бірдейлерін топтастыру",
    "hideDescription": "Сипаттаманы жасыру",
    "history": "Тарих",
    "home": "Басты бет",
    "homeDownloadsShortcutMessage": "Интернетсіз тыңдауға болатын кітаптар.",
    "homeLibraryShortcutMessage": "Таңдаулы кітаптар мен сақталған дыбыстаулар.",
    "hoursLabel": "{hours} сағ",
    "hoursMinutesLabel": "{hours} сағ {minutes} мин",
    "info": "Ақпарат",
    "information": "Ақпарат",
    "izibSearchSubtitle": "Нақты дереккөздердің нәтижелері; карточкалар мен тараулар SourceConnector арқылы жүктеледі.",
    "kilobyteUnit": "КБ",
    "language": "Тіл",
    "later": "Кейін",
    "library": "Кітапхана",
    "libraryActionError": "Өзгерісті сақтау мүмкін болмады",
    "libraryLoadError": "Кітапхананы жүктеу мүмкін болмады",
    "librarySourcesMessage": "Кітаптарды сақтаңыз немесе тыңдауды бастаңыз — олар осында пайда болады.",
    "listening": "Тыңдап жатырмын",
    "loading": "Жүктелуде...",
    "megabyteUnit": "МБ",
    "minutesLabel": "{minutes} мин",
    "mobileNavigationDownloads": "Жүктеулер",
    "mobileNavigationSettings": "Баптаулар",
    "mockDataNotice": "Қолданба қаңқасы жергілікті сынақ деректерімен жұмыс істейді. Дереккөздер жеке қабат арқылы қосылады.",
    "mute": "Дыбысты өшіру",
    "narratorUnknown": "Дыбыстаушы көрсетілмеген",
    "navigationTabLabel": "{label}\nҚойынды {index} / {total}",
    "nextChapter": "Келесі тарау",
    "nextTabs": "Келесі қойындылар",
    "noBookmarks": "Бетбелгілер жоқ",
    "noInternetMessage": "Wi-Fi немесе мобильді желіні тексеріп, қайталап көріңіз.",
    "noInternetTitle": "Интернет байланысы жоқ",
    "noSearchResults": "Ештеңе табылмады",
    "noSearchResultsMessage": "Басқа атауды, авторды немесе дыбыстаушыны енгізіп көріңіз.",
    "noUpdatesAvailable": "Жаңартулар жоқ",
    "nowPlaying": "Қазір ойнатылуда",
    "offlineDownloads": "Офлайн үшін жүктелген",
    "openDownloads": "Жүктеулерді ашу",
    "openFullPlayer": "Толық ойнатқышты ашу",
    "openPlayer": "Ойнатқышты ашу",
    "openSearch": "Іздеуді ашу",
    "openThemePreview": "Тақырыпты алдын ала қарауды ашу",
    "otherNarrations": "Басқа дыбыстаулар",
    "otherVersions": "Басқа нұсқалар",
    "paid": "Ақылы",
    "partialSearchRetry": "Іздеуді қайталау",
    "partialSearchSources": "Жауап бермегендер: {names}",
    "partialSourceFailures.few": "{count} дереккөз қате қайтарды",
    "partialSourceFailures.many": "{count} дереккөз қате қайтарды",
    "partialSourceFailures.one": "{count} дереккөз қате қайтарды",
    "pause": "Кідірту",
    "pauseDownload": "Жүктеуді кідірту",
    "paused": "Кідіртілген",
    "peopleAndOthers": "{names} және басқалар",
    "play": "Тыңдау",
    "playback": "Ойнату",
    "playbackSource": "Дереккөз",
    "playbackSpeed": "Ойнату жылдамдығы",
    "player": "Ойнатқыш",
    "playerSettingsHint": "Жылдамдық, ұйқы таймері және тарауларды басқару толық ойнатқышта орналасқан.",
    "previewButtons": "Батырмалар",
    "previewCards": "Карточкалар",
    "previewChips": "Белгілер",
    "previewInputs": "Енгізу өрістері",
    "previewStates": "Күйлер",
    "previousChapter": "Алдыңғы тарау",
    "previousTabs": "Алдыңғы қойындылар",
    "projectWebsite": "Жоба сайты",
    "proxy": "Прокси",
    "queued": "Кезекте",
    "queuedDownloads": "Кезек",
    "ratingOutOfFive": "{rating} / 5",
    "realSourceHomeMessage": "Іздеу, карточкалар, тараулар, ойнатқыш және жүктеулер Izib, Akniga, Yakniga, Knigavuhe, Knigoblud және Baza Knig дереккөздеріне қосылған.",
    "realSourceHomeTitle": "Кітап табыңыз",
    "recentSearches": "Іздеу тарихы",
    "recommended": "Сынақ деректеріндегі ұсыныстар",
    "removeFavorite": "Таңдаулылардан алып тастау",
    "removeFromLater": "«Кейін» тізімінен алып тастау",
    "resume": "Жалғастыру",
    "resumeDownload": "Жүктеуді жалғастыру",
    "retry": "Қайталау",
    "rewind15": "15 секунд артқа",
    "saveBookmark": "Бетбелгіні сақтау",
    "savedBookMediaUnavailable": "Сақталған аудиотараулар жоқ. Кітапты дереккөзден табыңыз.",
    "savedBookNotFound": "Кітап кітапханадан табылмады",
    "savedBookPlaybackError": "Ойнатуды бастау мүмкін болмады",
    "search": "Іздеу",
    "searchByAuthor": "Автор",
    "searchByGenre": "Жанр",
    "searchByNarrator": "Дыбыстаушы",
    "searchBySeries": "Топтама",
    "searchByTitle": "Атауы",
    "searchHint": "Атауы, авторы, дыбыстаушысы, топтамасы немесе жанры",
    "searchHistoryEmptyMessage": "Соңғы сұрауларыңыз осында көрсетіледі — оларды қайталауға немесе жоюға болады.",
    "searchReadyMessage": "Іздеу Izib, Akniga, Yakniga, Knigavuhe, Knigoblud және Baza Knig дереккөздеріне қосылған.",
    "searchReadyTitle": "Іздеу сұрауын енгізіңіз",
    "searchResults": "Нәтижелер",
    "searchScope": "Іздеу өрісі",
    "searchShortQueryMessage": "Кемінде 2 таңба енгізіңіз.",
    "searchShortQueryTitle": "Сұрау тым қысқа",
    "searchingSources": "Дереккөздерден ізделуде...",
    "selectAtLeastOneSearchKind": "Кемінде бір іздеу өрісін таңдаңыз.",
    "selectAtLeastOneSource": "Кемінде бір дереккөзді таңдаңыз",
    "selectedSourcesCount.few": "{count} дереккөз қосылған",
    "selectedSourcesCount.many": "{count} дереккөз қосылған",
    "selectedSourcesCount.one": "{count} дереккөз қосылған",
    "series": "Топтама",
    "settings": "Баптаулар",
    "settingsApplication": "Қолданба",
    "settingsContent": "Мазмұн және сақтау",
    "settingsPersonalization": "Жекелендіру",
    "settingsSections": "Баптау бөлімдері",
    "share": "Бөлісу",
    "shareLinkCopied": "Сілтеме көшірілді",
    "shareSlovofonLink": "Slovofon сілтемесі",
    "shareSourceLink": "Дереккөз сілтемесі",
    "showFullDescription": "Толық көрсету",
    "showMoreChapters.few": "Тағы {count} тарау көрсету",
    "showMoreChapters.many": "Тағы {count} тарау көрсету",
    "showMoreChapters.one": "Тағы {count} тарау көрсету",
    "showPercentOnCovers": "Мұқабалардағы тыңдалу пайызы",
    "showSourceOnCards": "Карточкалардағы дереккөз атауы",
    "skipUpdate": "Бұл нұсқаны өткізіп жіберу",
    "sleepTimer": "Ұйқы таймері",
    "sleepTimerUntilChapterEnd": "Тарау аяқталғанша",
    "snackbarPreview": "Қалқымалы хабарлама",
    "sort": "Сұрыптау",
    "sortByDuration": "ұзақтығы",
    "sortByRating": "рейтинг",
    "sortByRelevance": "сәйкестік",
    "sortByTitle": "атауы",
    "sortByYear": "жыл",
    "sourceDisplayName.akniga": "Akniga",
    "sourceDisplayName.bazaKnig": "Baza Knig",
    "sourceDisplayName.izib": "Izib",
    "sourceDisplayName.knigavuhe": "Knigavuhe",
    "sourceDisplayName.knigoblud": "Knigoblud",
    "sourceDisplayName.yakniga": "Yakniga",
    "sourceDownloadDisabled": "Бұл дереккөзден жүктеу баптауларда өшірілген",
    "sourceFilter": "Дереккөздер",
    "sourcePage": "Дереккөз сайтындағы бет",
    "sourcePageOpenError": "Дереккөз бетін ашу мүмкін болмады",
    "sourceResultsCount.few": "{count} нәтиже",
    "sourceResultsCount.many": "{count} нәтиже",
    "sourceResultsCount.one": "{count} нәтиже",
    "sourceSearchDisabled": "Іздеуден шығарылған",
    "sourceSearchEnabled": "Іздеуге қосылған",
    "sourceSearchError": "Іздеу орындалмады",
    "sourceStats": "Дереккөз статистикасы",
    "sourceStreamingDisabled": "Бұл дереккөзден ойнату баптауларда өшірілген",
    "sourceUnavailableMessage": "Кейінірек қайталап көріңіз немесе байланысты тексеріңіз.",
    "sourceUnavailableTitle": "«{sourceName}» дереккөзі қолжетімсіз",
    "sources": "Дереккөздер",
    "startedBooks": "Басталған кітаптар",
    "subscription": "Жазылым",
    "success": "Сәтті",
    "systemLanguage": "Жүйе тілі",
    "telegramChannel": "Telegram арнасы",
    "telegramChat": "Telegram чаты",
    "telegramSupportBot": "Telegram қолдау боты",
    "terabyteUnit": "ТБ",
    "textSize": "Мәтін өлшемі",
    "textSizeHint": "100% — жүйедегі мәтін өлшемі. Өзгерістер жүгірткіні жібергенде қолданылады.",
    "textSizeLabel": "Мәтін өлшемі: {percent}%",
    "textSizePreview": "Қолданбадағы мәтін осылай көрінеді.",
    "textSizeReset": "100%-ға қайтару",
    "theme": "Тақырып",
    "themeAmoled": "AMOLED",
    "themeDark": "Қараңғы",
    "themeLight": "Ашық",
    "themeModeLabel": "Тақырып: {value}",
    "themePreview": "Тақырыпты алдын ала қарау",
    "themeSystem": "Жүйелік",
    "unknown": "Белгісіз",
    "unknownSize": "Көлемі белгісіз",
    "updateAvailableMessage": "{version} нұсқасы қолжетімді. Жаңарту көлемі: {size}.",
    "updateAvailableTitle": "Жаңарту қолжетімді",
    "updateChannel": "Жаңарту арнасы",
    "updateCheckFailed": "Жаңартуларды тексеру мүмкін болмады",
    "updateCheckFailedMessage": "Байланысты тексеріп, «Қайталау» түймесін басыңыз.",
    "updateDownloadFailed": "Жаңартуды жүктеу мүмкін болмады",
    "updateDownloadFailedMessage": "Байланысты тексеріп, «Қайталау» түймесін басыңыз.",
    "updateDownloadProgress": "{total} ішінен {downloaded} · {speed}/с",
    "updateDownloadZip": "ZIP жүктеп алу",
    "updateDownloading": "Жаңарту жүктелуде...",
    "updateInstallFailed": "Жаңартуды іске қосу мүмкін болмады",
    "updateInstallFailedMessage": "Жаңарту файлын дайындау немесе ашу мүмкін болмады. Жүйе рұқсаттарын тексеріп, «Қайталау» түймесін басыңыз. Қолданба автоматты түрде жабылмайды.",
    "updateInstallPermissionRequired": "Slovofon үшін APK орнатуға рұқсат беріп, «Жаңарту» түймесін қайта басыңыз.",
    "updateInstallerHint": "Файл тексерілгеннен кейін орнатқыш ашылады. Оның нұсқауларын орындаңыз; баптаулар, тыңдалу барысы және жүктелген кітаптар сақталады.",
    "updateInstallerStarted": "Жаңарту орнатқышы ашылды",
    "updateLater": "Кейін",
    "updateManualDownloadHint": "Windows жүйесіндегі орнату түрін сенімді анықтау мүмкін болмады. Шығарылымдар бетінен сәйкес файлды таңдаңыз; қолданба автоматты түрде алмастырылмайды.",
    "updateNotesAlert.caution": "Назар аударыңыз",
    "updateNotesAlert.important": "Маңызды",
    "updateNotesAlert.note": "Ескертпе",
    "updateNotesAlert.tip": "Кеңес",
    "updateNotesAlert.warning": "Ескерту",
    "updateNotesLinkFailed": "Сілтемені ашу мүмкін болмады. Браузердің орнатылғанын тексеріңіз.",
    "updateNotesRemoteHint": "Жоғары және төмен — айналдыру. Оңға — сілтемелерге өту.",
    "updateNotesTruncated": "Сипаттаманың бір бөлігі көрсетілген. Толық мәтін шығарылым бетінде қолжетімді.",
    "updateNow": "Жаңарту",
    "updateOpenReleases": "Шығарылымдар бетін ашу",
    "updatePortableHint": "ZIP мұрағаты жүктеліп, тексеріледі. Содан кейін Slovofon қолданбасын жауып, мұрағатты жаңа қалтаға шығарыңыз. Пайдаланушы деректері мен жүктелген кітаптар қалталарын жоймаңыз.",
    "updatePortableReady": "Мұрағат тексеріліп, жүктеу қалтасы ашылды. Slovofon қолданбасын жауып, ZIP мұрағатын жаңа қалтаға шығарыңыз.",
    "updatePreparingTitle": "Жаңартуды тексеру және іске қосу",
    "updateReleaseNotes": "Не жаңалық",
    "updateReleasePageFailed": "Шығарылымдар бетін ашу мүмкін болмады. Қайталап көріңіз.",
    "updateSkipFailed": "Нұсқаны өткізіп жіберуді сақтау мүмкін болмады. Қайталап көріңіз немесе «Кейін» түймесін басыңыз.",
    "updateUnsupportedPlatform": "Бұл платформаға сәйкес жаңарту файлы жоқ",
    "volume": "Дыбыс деңгейі",
    "warning": "Назар аударыңыз",
  },
  "be": {
    "aboutApp": "Пра праграму",
    "aboutAppHint": "Версія, зборка і спасылкі праекта",
    "accentColor": "Акцэнтны колер",
    "accentDefault": "Па змаўчанні",
    "accentGold": "Залаты",
    "accentGreen": "Зялёны",
    "accentRed": "Чырвоны",
    "accentTeal": "Бірузовы",
    "activeDownloads": "Актыўныя",
    "addBookmark": "Дадаць закладку",
    "addFavorite": "У абранае",
    "addToLater": "Адкласці",
    "all": "Усе",
    "allChapters": "Усе раздзелы",
    "allSources": "Усе крыніцы",
    "animations": "Анімацыі",
    "animationsFull": "Поўныя",
    "animationsOff": "Выключаны",
    "animationsReduced": "Скарочаныя",
    "appTitle": "Slovofon",
    "appUpdates": "Абнаўленні",
    "appUpdatesHint": "Праверыць новую версію",
    "appVersion": "Версія",
    "appearance": "Выгляд",
    "apply": "Гатова",
    "audioYearLabel": "Год агучвання: {year}",
    "bookActions": "Дзеянні з кнігай",
    "bookDetails": "Картка кнігі",
    "bookDetailsLoadFailedMessage": "Не ўдалося загрузіць даныя з крыніцы «{sourceName}».",
    "bookDetailsLoadFailedTitle": "Не ўдалося адкрыць картку кнігі",
    "bookFragment": "Азнаямленчы ўрывак",
    "bookNotFoundMessage": "Крыніца «{sourceName}» не знайшла гэту кнігу. Магчыма, старонка была выдалена.",
    "bookProgress": "Прагрэс кнігі",
    "bookmarkAdded": "Закладка дададзена",
    "bookmarkNote": "Нататка",
    "bookmarkRemoved": "Закладка выдалена",
    "bookmarkUnavailable": "Не ўдалося адкрыць кнігу для гэтай закладкі",
    "bookmarks": "Закладкі",
    "booksCount.few": "{count} кнігі",
    "booksCount.many": "{count} кніг",
    "booksCount.one": "{count} кніга",
    "buildNumber": "Нумар зборкі",
    "byteUnit": "Б",
    "bytesPerSecond": "{bytes}/с",
    "cacheAndMetadata": "Кэш картак",
    "cacheAndMetadataHint": "Вокладкі і звесткі пра кнігі даступныя без інтэрнэту і абнаўляюцца пры адкрыцці карткі.",
    "cacheClearFailed": "Не ўдалося ачысціць кэш. Паспрабуйце яшчэ раз.",
    "cacheCleared": "Кэш ачышчаны: {books}, {size}",
    "cacheSize": "Памер: {value}",
    "calculatingTotalSize": "памер удакладняецца",
    "cancel": "Скасаваць",
    "cancelDownload": "Скасаваць спампоўку",
    "cards": "Карткі",
    "chapterNumber": "Раздзел {number}",
    "chapterPosition": "Раздзел {current} з {total}",
    "chapters": "Раздзелы",
    "chaptersCount.few": "{count} раздзелы",
    "chaptersCount.many": "{count} раздзелаў",
    "chaptersCount.one": "{count} раздзел",
    "checkingUpdates": "Праверка абнаўленняў...",
    "clearCacheSafetyHint": "Незавершаныя спампоўкі таксама захаваюцца.",
    "clearCardCache": "Ачысціць кэш картак",
    "clearCardCacheConfirm": "Выдаліць вокладкі і звесткі пра кнігі без спампаваных файлаў? Спампаваныя кнігі і раздзелы, абранае, гісторыя і прагрэс захаваюцца.",
    "collapseChapters": "Згарнуць раздзелы",
    "colorBrightness": "Яркасць",
    "colorHue": "Тон",
    "colorPreview": "Перадпрагляд",
    "colorSaturation": "Насычанасць",
    "compactCards": "Кампактныя карткі",
    "completedDownloads": "Завершаныя",
    "continueListening": "Працягнуць праслухоўванне",
    "continuePlayback": "Працягнуць",
    "currentAndNextChapters": "Бягучы і наступныя",
    "customColor": "Свой колер",
    "dataAndDownloads": "Даныя і спампоўкі",
    "deleteBookmark": "Выдаліць закладку?",
    "deleteBookmarkAction": "Выдаліць",
    "deleteBookmarkDescription": "Закладка будзе выдалена. Кніга і прагрэс праслухоўвання захаваюцца.",
    "deleteDownloaded": "Выдаліць спампаванае",
    "deleteSearchHistoryEntry": "Выдаліць з гісторыі",
    "description": "Апісанне",
    "desktopLibraryLabel": "Аўдыякнігі",
    "details": "Падрабязней",
    "diagnostics": "Дыягностыка",
    "diagnosticsHint": "Перадпрагляд тэмы і бяспечная праверка станаў інтэрфейсу.",
    "disableSleepTimer": "Выключыць таймер",
    "disabled": "Выключана",
    "download": "Спампаваць",
    "downloadBook": "Спампаваць кнігу",
    "downloadChaptersProgress.few": "{completed} з {total} раздзелаў",
    "downloadChaptersProgress.many": "{completed} з {total} раздзелаў",
    "downloadChaptersProgress.one": "{completed} з {total} раздзела",
    "downloadMetadataUnavailable": "Адкрыйце кнігу праз пошук, каб аднавіць яе даныя. Спампаваныя файлы захаваны.",
    "downloadMetadataUnavailableTitle": "Даныя кнігі недаступныя",
    "downloadQueuedMessage": "Кніга дададзена ў спампоўкі",
    "downloaded": "Спампаваныя",
    "downloadedBooksPreserved": "Спампаваныя кнігі не выдаляюцца",
    "downloading": "Спампоўваецца",
    "downloads": "Спампоўкі",
    "downloadsQueueSubtitle": "Чарга, прагрэс, прыпыненне, паўтор і выдаленне афлайн-файлаў.",
    "downloadsSettingsHint": "Чарга, прыпыненне, паўтор і выдаленне афлайн-файлаў знаходзяцца на ўкладцы спамповак.",
    "emptyBookmarksShelf": "Няма закладак",
    "emptyBookmarksShelfMessage": "Дадайце закладку ў плэеры, каб вярнуцца да патрэбнага моманту.",
    "emptyDownloadedShelf": "Няма спампаваных кніг",
    "emptyDownloadedShelfMessage": "Спампуйце кнігу, каб слухаць без інтэрнэту.",
    "emptyDownloads": "Спамповак пакуль няма",
    "emptyDownloadsMessage": "Знайдзіце кнігу і спампуйце яе раздзелы, каб слухаць без інтэрнэту.",
    "emptyFavoritesShelf": "У абраным пакуль пуста",
    "emptyFavoritesShelfMessage": "Дадавайце ўпадабаныя кнігі з дапамогай сэрца.",
    "emptyFinishedShelf": "Няма праслуханых кніг",
    "emptyFinishedShelfMessage": "Тут з’явяцца кнігі, якія вы даслухалі.",
    "emptyHistoryShelf": "Гісторыя праслухоўвання пустая",
    "emptyHistoryShelfMessage": "Кнігі, якія вы запускалі, будуць паказаны тут.",
    "emptyLaterShelf": "Няма адкладзеных кніг",
    "emptyLaterShelfMessage": "Выберыце «Адкласці» ў меню кнігі, каб захаваць яе на потым.",
    "emptyLibrary": "Бібліятэка пакуль пустая",
    "emptyListeningShelf": "Пакуль нічога не слухаеце",
    "emptyListeningShelfMessage": "Пачніце слухаць кнігу — тут з’явіцца ваш прагрэс.",
    "enabled": "Уключана",
    "enabledInSearch": "Выкарыстоўваюцца ў пошуку",
    "failed": "Памылка",
    "failedDownloads": "Памылкі",
    "favoriteAdded": "Дададзена ў абранае",
    "favoriteRemoved": "Выдалена з абранага",
    "favorites": "Абранае",
    "filter": "Фільтр",
    "filteredNoSearchResults": "Крыніца вярнула даныя, але ніводзін вынік не адпавядае ўсім словам запыту.",
    "finished": "Праслухана",
    "forward15": "Наперад на 15 секунд",
    "free": "Бясплатна",
    "fullPlayer": "Поўны плэер",
    "genre": "Жанр",
    "gigabyteUnit": "ГБ",
    "githubRepository": "GitHub праграмы",
    "goToCurrentChapter": "Да бягучага раздзела",
    "groupedDuplicates": "Групаваць аднолькавыя",
    "hideDescription": "Схаваць апісанне",
    "history": "Гісторыя",
    "home": "Галоўная",
    "homeDownloadsShortcutMessage": "Кнігі, якія можна слухаць без інтэрнэту.",
    "homeLibraryShortcutMessage": "Абраныя кнігі і захаваныя агучванні.",
    "hoursLabel": "{hours} гадз",
    "hoursMinutesLabel": "{hours} гадз {minutes} хв",
    "info": "Інфармацыя",
    "information": "Інфармацыя",
    "izibSearchSubtitle": "Вынікі рэальных крыніц; карткі і раздзелы загружаюцца праз SourceConnector.",
    "kilobyteUnit": "КБ",
    "language": "Мова",
    "later": "Пазней",
    "library": "Бібліятэка",
    "libraryActionError": "Не ўдалося захаваць змяненне",
    "libraryLoadError": "Не ўдалося загрузіць бібліятэку",
    "librarySourcesMessage": "Захоўвайце кнігі або пачніце слухаць — яны з’явяцца тут.",
    "listening": "Слухаю",
    "loading": "Загрузка...",
    "megabyteUnit": "МБ",
    "minutesLabel": "{minutes} хв",
    "mobileNavigationDownloads": "Спампоўкі",
    "mobileNavigationSettings": "Налады",
    "mockDataNotice": "Каркас працуе на лакальных тэставых даных. Крыніцы будуць падлучаны праз асобны слой.",
    "mute": "Без гуку",
    "narratorUnknown": "Чытальнік не пазначаны",
    "navigationTabLabel": "{label}\nУкладка {index} з {total}",
    "nextChapter": "Наступны раздзел",
    "nextTabs": "Наступныя ўкладкі",
    "noBookmarks": "Няма закладак",
    "noInternetMessage": "Праверце Wi-Fi або мабільную сетку і паўтарыце спробу.",
    "noInternetTitle": "Няма злучэння з інтэрнэтам",
    "noSearchResults": "Нічога не знойдзена",
    "noSearchResultsMessage": "Паспрабуйце іншую назву, аўтара або чытальніка.",
    "noUpdatesAvailable": "Абнаўленняў няма",
    "nowPlaying": "Зараз гучыць",
    "offlineDownloads": "Спампаваныя для афлайну",
    "openDownloads": "Адкрыць спампоўкі",
    "openFullPlayer": "Адкрыць поўны плэер",
    "openPlayer": "Адкрыць плэер",
    "openSearch": "Адкрыць пошук",
    "openThemePreview": "Адкрыць перадпрагляд тэмы",
    "otherNarrations": "Іншыя агучванні",
    "otherVersions": "Іншыя версіі",
    "paid": "Платна",
    "partialSearchRetry": "Паўтарыць пошук",
    "partialSearchSources": "Не адказалі: {names}",
    "partialSourceFailures.few": "{count} крыніцы вярнулі памылку",
    "partialSourceFailures.many": "{count} крыніц вярнулі памылку",
    "partialSourceFailures.one": "{count} крыніца вярнула памылку",
    "pause": "Паўза",
    "pauseDownload": "Прыпыніць спампоўку",
    "paused": "Прыпынена",
    "peopleAndOthers": "{names} і інш.",
    "play": "Слухаць",
    "playback": "Прайграванне",
    "playbackSource": "Крыніца",
    "playbackSpeed": "Хуткасць прайгравання",
    "player": "Плэер",
    "playerSettingsHint": "Хуткасць, таймер сну і кіраванне раздзеламі знаходзяцца ў поўным плэеры.",
    "previewButtons": "Кнопкі",
    "previewCards": "Карткі",
    "previewChips": "Чыпы",
    "previewInputs": "Палі ўводу",
    "previewStates": "Станы",
    "previousChapter": "Папярэдні раздзел",
    "previousTabs": "Папярэднія ўкладкі",
    "projectWebsite": "Сайт праекта",
    "proxy": "Проксі",
    "queued": "У чарзе",
    "queuedDownloads": "Чарга",
    "ratingOutOfFive": "{rating} з 5",
    "realSourceHomeMessage": "Пошук, карткі, раздзелы, плэер і спампоўкі падлучаны да крыніц Izib, Akniga, Yakniga, Knigavuhe, Knigoblud і Baza Knig.",
    "realSourceHomeTitle": "Знайдзіце кнігу",
    "recentSearches": "Гісторыя пошуку",
    "recommended": "Рэкамендацыі на тэставых даных",
    "removeFavorite": "Прыбраць з абранага",
    "removeFromLater": "Прыбраць з «Пазней»",
    "resume": "Працягнуць",
    "resumeDownload": "Працягнуць спампоўку",
    "retry": "Паўтарыць",
    "rewind15": "Назад на 15 секунд",
    "saveBookmark": "Захаваць закладку",
    "savedBookMediaUnavailable": "Няма захаваных аўдыяраздзелаў. Знайдзіце кнігу ў крыніцы.",
    "savedBookNotFound": "Кніга не знойдзена ў бібліятэцы",
    "savedBookPlaybackError": "Не ўдалося пачаць прайграванне",
    "search": "Пошук",
    "searchByAuthor": "Аўтар",
    "searchByGenre": "Жанр",
    "searchByNarrator": "Чытальнік",
    "searchBySeries": "Цыкл",
    "searchByTitle": "Назва",
    "searchHint": "Назва, аўтар, чытальнік, цыкл або жанр",
    "searchHistoryEmptyMessage": "Тут з’явяцца вашы нядаўнія запыты — іх можна паўтарыць або выдаліць.",
    "searchReadyMessage": "Пошук падлучаны да крыніц Izib, Akniga, Yakniga, Knigavuhe, Knigoblud і Baza Knig.",
    "searchReadyTitle": "Увядзіце запыт",
    "searchResults": "Вынікі",
    "searchScope": "Шукаць па",
    "searchShortQueryMessage": "Увядзіце не менш за 2 сімвалы.",
    "searchShortQueryTitle": "Запыт занадта кароткі",
    "searchingSources": "Пошук у крыніцах...",
    "selectAtLeastOneSearchKind": "Выберыце хаця б адно поле пошуку.",
    "selectAtLeastOneSource": "Выберыце хаця б адну крыніцу",
    "selectedSourcesCount.few": "{count} крыніцы ўключаны",
    "selectedSourcesCount.many": "{count} крыніц уключана",
    "selectedSourcesCount.one": "{count} крыніца ўключана",
    "series": "Цыкл",
    "settings": "Налады",
    "settingsApplication": "Праграма",
    "settingsContent": "Змесціва і сховішча",
    "settingsPersonalization": "Персаналізацыя",
    "settingsSections": "Раздзелы налад",
    "share": "Падзяліцца",
    "shareLinkCopied": "Спасылка скапіявана",
    "shareSlovofonLink": "Спасылка Slovofon",
    "shareSourceLink": "Спасылка крыніцы",
    "showFullDescription": "Паказаць цалкам",
    "showMoreChapters.few": "Паказаць яшчэ {count} раздзелы",
    "showMoreChapters.many": "Паказаць яшчэ {count} раздзелаў",
    "showMoreChapters.one": "Паказаць яшчэ {count} раздзел",
    "showPercentOnCovers": "Працэнт праслухоўвання на вокладках",
    "showSourceOnCards": "Назва крыніцы на картках",
    "skipUpdate": "Прапусціць версію",
    "sleepTimer": "Таймер сну",
    "sleepTimerUntilChapterEnd": "Да канца раздзела",
    "snackbarPreview": "Усплывальнае паведамленне",
    "sort": "Сартаванне",
    "sortByDuration": "працягласць",
    "sortByRating": "рэйтынг",
    "sortByRelevance": "адпаведнасць",
    "sortByTitle": "назва",
    "sortByYear": "год",
    "sourceDisplayName.akniga": "Akniga",
    "sourceDisplayName.bazaKnig": "Baza Knig",
    "sourceDisplayName.izib": "Izib",
    "sourceDisplayName.knigavuhe": "Knigavuhe",
    "sourceDisplayName.knigoblud": "Knigoblud",
    "sourceDisplayName.yakniga": "Yakniga",
    "sourceDownloadDisabled": "Спампоўка з гэтай крыніцы выключана ў наладах",
    "sourceFilter": "Крыніцы",
    "sourcePage": "Старонка на сайце крыніцы",
    "sourcePageOpenError": "Не ўдалося адкрыць старонку крыніцы",
    "sourceResultsCount.few": "{count} вынікі",
    "sourceResultsCount.many": "{count} вынікаў",
    "sourceResultsCount.one": "{count} вынік",
    "sourceSearchDisabled": "Выключана з пошуку",
    "sourceSearchEnabled": "Уключана ў пошук",
    "sourceSearchError": "Не ўдалося выканаць пошук",
    "sourceStats": "Статыстыка крыніцы",
    "sourceStreamingDisabled": "Прайграванне з гэтай крыніцы выключана ў наладах",
    "sourceUnavailableMessage": "Паўтарыце спробу пазней або праверце злучэнне.",
    "sourceUnavailableTitle": "Крыніца «{sourceName}» недаступная",
    "sources": "Крыніцы",
    "startedBooks": "Пачатыя кнігі",
    "subscription": "Падпіска",
    "success": "Паспяхова",
    "systemLanguage": "Мова сістэмы",
    "telegramChannel": "Telegram-канал",
    "telegramChat": "Telegram-чат",
    "telegramSupportBot": "Telegram-бот падтрымкі",
    "terabyteUnit": "ТБ",
    "textSize": "Памер тэксту",
    "textSizeHint": "100% — сістэмны памер тэксту. Змены ўжываюцца пасля адпускання паўзунка.",
    "textSizeLabel": "Памер тэксту: {percent}%",
    "textSizePreview": "Так будзе выглядаць тэкст у праграме.",
    "textSizeReset": "Вярнуць 100%",
    "theme": "Тэма",
    "themeAmoled": "AMOLED",
    "themeDark": "Цёмная",
    "themeLight": "Светлая",
    "themeModeLabel": "Тэма: {value}",
    "themePreview": "Перадпрагляд тэмы",
    "themeSystem": "Сістэмная",
    "unknown": "Невядома",
    "unknownSize": "Памер невядомы",
    "updateAvailableMessage": "Даступна версія {version}. Памер абнаўлення: {size}.",
    "updateAvailableTitle": "Даступна абнаўленне",
    "updateChannel": "Канал абнаўленняў",
    "updateCheckFailed": "Не ўдалося праверыць абнаўленні",
    "updateCheckFailedMessage": "Праверце злучэнне і націсніце «Паўтарыць».",
    "updateDownloadFailed": "Не ўдалося спампаваць абнаўленне",
    "updateDownloadFailedMessage": "Праверце злучэнне і націсніце «Паўтарыць».",
    "updateDownloadProgress": "{downloaded} з {total} · {speed}/с",
    "updateDownloadZip": "Спампаваць ZIP",
    "updateDownloading": "Абнаўленне спампоўваецца...",
    "updateInstallFailed": "Не ўдалося запусціць абнаўленне",
    "updateInstallFailedMessage": "Не ўдалося падрыхтаваць або адкрыць файл абнаўлення. Праверце дазволы сістэмы і націсніце «Паўтарыць». Праграма не будзе закрыта аўтаматычна.",
    "updateInstallPermissionRequired": "Дазвольце ўсталяванне APK для Slovofon і націсніце «Абнавіць» яшчэ раз.",
    "updateInstallerHint": "Пасля праверкі файла адкрыецца ўсталёўшчык. Выконвайце яго інструкцыі; налады, прагрэс і спампаваныя кнігі захаваюцца.",
    "updateInstallerStarted": "Усталёўшчык абнаўлення адкрыты",
    "updateLater": "Пазней",
    "updateManualDownloadHint": "Не ўдалося надзейна вызначыць тып усталявання Windows. Выберыце адпаведны файл на старонцы выпускаў; праграма не будзе заменена аўтаматычна.",
    "updateNotesAlert.caution": "Увага",
    "updateNotesAlert.important": "Важна",
    "updateNotesAlert.note": "Заўвага",
    "updateNotesAlert.tip": "Парада",
    "updateNotesAlert.warning": "Папярэджанне",
    "updateNotesLinkFailed": "Не ўдалося адкрыць спасылку. Праверце, ці ўсталяваны браўзер.",
    "updateNotesRemoteHint": "Уверх і ўніз — пракрутка. Управа — пераход да спасылак.",
    "updateNotesTruncated": "Паказана частка апісання. Поўны тэкст даступны на старонцы выпуску.",
    "updateNow": "Абнавіць",
    "updateOpenReleases": "Адкрыць старонку выпускаў",
    "updatePortableHint": "ZIP-архіў будзе спампаваны і правераны. Затым закрыйце Slovofon і распакуйце архіў у новую папку. Не выдаляйце папкі з карыстальніцкімі данымі і спампаванымі кнігамі.",
    "updatePortableReady": "Архіў правераны; адкрыта папка спампоўкі. Закрыйце Slovofon і распакуйце ZIP у новую папку.",
    "updatePreparingTitle": "Праверка і запуск абнаўлення",
    "updateReleaseNotes": "Што новага",
    "updateReleasePageFailed": "Не ўдалося адкрыць старонку выпускаў. Паўтарыце спробу.",
    "updateSkipFailed": "Не ўдалося захаваць пропуск версіі. Паўтарыце спробу або націсніце «Пазней».",
    "updateUnsupportedPlatform": "Для гэтай платформы няма адпаведнага файла абнаўлення",
    "volume": "Гучнасць",
    "warning": "Увага",
  },
  "uk": {
    "aboutApp": "Про застосунок",
    "aboutAppHint": "Версія, збірка та посилання проєкту",
    "accentColor": "Акцентний колір",
    "accentDefault": "За замовчуванням",
    "accentGold": "Золотий",
    "accentGreen": "Зелений",
    "accentRed": "Червоний",
    "accentTeal": "Бірюзовий",
    "activeDownloads": "Активні",
    "addBookmark": "Додати закладку",
    "addFavorite": "До улюбленого",
    "addToLater": "Відкласти",
    "all": "Усі",
    "allChapters": "Усі розділи",
    "allSources": "Усі джерела",
    "animations": "Анімації",
    "animationsFull": "Повні",
    "animationsOff": "Вимкнені",
    "animationsReduced": "Скорочені",
    "appTitle": "Slovofon",
    "appUpdates": "Оновлення",
    "appUpdatesHint": "Перевірити нову версію",
    "appVersion": "Версія",
    "appearance": "Зовнішній вигляд",
    "apply": "Готово",
    "audioYearLabel": "Рік озвучення: {year}",
    "bookActions": "Дії з книгою",
    "bookDetails": "Картка книги",
    "bookDetailsLoadFailedMessage": "Не вдалося завантажити дані з джерела «{sourceName}».",
    "bookDetailsLoadFailedTitle": "Не вдалося відкрити картку книги",
    "bookFragment": "Ознайомлювальний уривок",
    "bookNotFoundMessage": "Джерело «{sourceName}» не знайшло цю книгу. Можливо, сторінку видалено.",
    "bookProgress": "Прогрес книги",
    "bookmarkAdded": "Закладку додано",
    "bookmarkNote": "Нотатка",
    "bookmarkRemoved": "Закладку видалено",
    "bookmarkUnavailable": "Не вдалося відкрити книгу для цієї закладки",
    "bookmarks": "Закладки",
    "booksCount.few": "{count} книги",
    "booksCount.many": "{count} книг",
    "booksCount.one": "{count} книга",
    "buildNumber": "Номер збірки",
    "byteUnit": "Б",
    "bytesPerSecond": "{bytes}/с",
    "cacheAndMetadata": "Кеш карток",
    "cacheAndMetadataHint": "Обкладинки та відомості про книги доступні без інтернету й оновлюються під час відкриття картки.",
    "cacheClearFailed": "Не вдалося очистити кеш. Спробуйте ще раз.",
    "cacheCleared": "Кеш очищено: {books}, {size}",
    "cacheSize": "Розмір: {value}",
    "calculatingTotalSize": "розмір уточнюється",
    "cancel": "Скасувати",
    "cancelDownload": "Скасувати завантаження",
    "cards": "Картки",
    "chapterNumber": "Розділ {number}",
    "chapterPosition": "Розділ {current} із {total}",
    "chapters": "Розділи",
    "chaptersCount.few": "{count} розділи",
    "chaptersCount.many": "{count} розділів",
    "chaptersCount.one": "{count} розділ",
    "checkingUpdates": "Перевірка оновлень...",
    "clearCacheSafetyHint": "Незавершені завантаження також збережуться.",
    "clearCardCache": "Очистити кеш карток",
    "clearCardCacheConfirm": "Видалити обкладинки та відомості про книги без завантажених файлів? Завантажені книги та розділи, улюблене, історія й прогрес збережуться.",
    "collapseChapters": "Згорнути розділи",
    "colorBrightness": "Яскравість",
    "colorHue": "Тон",
    "colorPreview": "Попередній перегляд",
    "colorSaturation": "Насиченість",
    "compactCards": "Компактні картки",
    "completedDownloads": "Завершені",
    "continueListening": "Продовжити прослуховування",
    "continuePlayback": "Продовжити",
    "currentAndNextChapters": "Поточний і наступні",
    "customColor": "Власний колір",
    "dataAndDownloads": "Дані та завантаження",
    "deleteBookmark": "Видалити закладку?",
    "deleteBookmarkAction": "Видалити",
    "deleteBookmarkDescription": "Закладку буде видалено. Книга та прогрес прослуховування збережуться.",
    "deleteDownloaded": "Видалити завантажене",
    "deleteSearchHistoryEntry": "Видалити з історії",
    "description": "Опис",
    "desktopLibraryLabel": "Аудіокниги",
    "details": "Докладніше",
    "diagnostics": "Діагностика",
    "diagnosticsHint": "Попередній перегляд теми та безпечна перевірка станів інтерфейсу.",
    "disableSleepTimer": "Вимкнути таймер",
    "disabled": "Вимкнено",
    "download": "Завантажити",
    "downloadBook": "Завантажити книгу",
    "downloadChaptersProgress.few": "{completed} із {total} розділів",
    "downloadChaptersProgress.many": "{completed} із {total} розділів",
    "downloadChaptersProgress.one": "{completed} із {total} розділу",
    "downloadMetadataUnavailable": "Відкрийте книгу через пошук, щоб відновити її дані. Завантажені файли збережено.",
    "downloadMetadataUnavailableTitle": "Дані книги недоступні",
    "downloadQueuedMessage": "Книгу додано до завантажень",
    "downloaded": "Завантажені",
    "downloadedBooksPreserved": "Завантажені книги не видаляються",
    "downloading": "Завантажується",
    "downloads": "Завантаження",
    "downloadsQueueSubtitle": "Черга, прогрес, призупинення, повтор і видалення офлайн-файлів.",
    "downloadsSettingsHint": "Черга, призупинення, повтор і видалення офлайн-файлів розташовані на вкладці завантажень.",
    "emptyBookmarksShelf": "Немає закладок",
    "emptyBookmarksShelfMessage": "Додайте закладку в програвачі, щоб повернутися до потрібного моменту.",
    "emptyDownloadedShelf": "Немає завантажених книг",
    "emptyDownloadedShelfMessage": "Завантажте книгу, щоб слухати без інтернету.",
    "emptyDownloads": "Завантажень поки немає",
    "emptyDownloadsMessage": "Знайдіть книгу та завантажте її розділи, щоб слухати без інтернету.",
    "emptyFavoritesShelf": "В улюбленому поки порожньо",
    "emptyFavoritesShelfMessage": "Додавайте книги, що сподобалися, за допомогою сердечка.",
    "emptyFinishedShelf": "Немає прослуханих книг",
    "emptyFinishedShelfMessage": "Тут з’являться книги, які ви дослухали.",
    "emptyHistoryShelf": "Історія прослуховування порожня",
    "emptyHistoryShelfMessage": "Книги, які ви запускали, будуть показані тут.",
    "emptyLaterShelf": "Немає відкладених книг",
    "emptyLaterShelfMessage": "Виберіть «Відкласти» в меню книги, щоб зберегти її на потім.",
    "emptyLibrary": "Бібліотека поки порожня",
    "emptyListeningShelf": "Поки нічого не слухаєте",
    "emptyListeningShelfMessage": "Почніть слухати книгу — тут з’явиться ваш прогрес.",
    "enabled": "Увімкнено",
    "enabledInSearch": "Використовуються в пошуку",
    "failed": "Помилка",
    "failedDownloads": "Помилки",
    "favoriteAdded": "Додано до улюбленого",
    "favoriteRemoved": "Видалено з улюбленого",
    "favorites": "Улюблене",
    "filter": "Фільтр",
    "filteredNoSearchResults": "Джерело повернуло дані, але жоден результат не відповідає всім словам запиту.",
    "finished": "Прослухано",
    "forward15": "Уперед на 15 секунд",
    "free": "Безкоштовно",
    "fullPlayer": "Повний програвач",
    "genre": "Жанр",
    "gigabyteUnit": "ГБ",
    "githubRepository": "GitHub застосунку",
    "goToCurrentChapter": "До поточного розділу",
    "groupedDuplicates": "Групувати однакові",
    "hideDescription": "Приховати опис",
    "history": "Історія",
    "home": "Головна",
    "homeDownloadsShortcutMessage": "Книги, які можна слухати без інтернету.",
    "homeLibraryShortcutMessage": "Улюблені книги та збережені озвучення.",
    "hoursLabel": "{hours} год",
    "hoursMinutesLabel": "{hours} год {minutes} хв",
    "info": "Інформація",
    "information": "Інформація",
    "izibSearchSubtitle": "Результати реальних джерел; картки та розділи завантажуються через SourceConnector.",
    "kilobyteUnit": "КБ",
    "language": "Мова",
    "later": "Пізніше",
    "library": "Бібліотека",
    "libraryActionError": "Не вдалося зберегти зміну",
    "libraryLoadError": "Не вдалося завантажити бібліотеку",
    "librarySourcesMessage": "Зберігайте книги або почніть слухати — вони з’являться тут.",
    "listening": "Слухаю",
    "loading": "Завантаження...",
    "megabyteUnit": "МБ",
    "minutesLabel": "{minutes} хв",
    "mobileNavigationDownloads": "Заванта­ження",
    "mobileNavigationSettings": "Налашту­вання",
    "mockDataNotice": "Каркас працює на локальних тестових даних. Джерела буде підключено через окремий шар.",
    "mute": "Без звуку",
    "narratorUnknown": "Читця не вказано",
    "navigationTabLabel": "{label}\nВкладка {index} із {total}",
    "nextChapter": "Наступний розділ",
    "nextTabs": "Наступні вкладки",
    "noBookmarks": "Немає закладок",
    "noInternetMessage": "Перевірте Wi-Fi або мобільну мережу та повторіть спробу.",
    "noInternetTitle": "Немає з’єднання з інтернетом",
    "noSearchResults": "Нічого не знайдено",
    "noSearchResultsMessage": "Спробуйте іншу назву, автора або читця.",
    "noUpdatesAvailable": "Оновлень немає",
    "nowPlaying": "Зараз відтворюється",
    "offlineDownloads": "Завантажені для офлайну",
    "openDownloads": "Відкрити завантаження",
    "openFullPlayer": "Відкрити повний програвач",
    "openPlayer": "Відкрити програвач",
    "openSearch": "Відкрити пошук",
    "openThemePreview": "Відкрити попередній перегляд теми",
    "otherNarrations": "Інші озвучення",
    "otherVersions": "Інші версії",
    "paid": "Платно",
    "partialSearchRetry": "Повторити пошук",
    "partialSearchSources": "Не відповіли: {names}",
    "partialSourceFailures.few": "{count} джерела повернули помилку",
    "partialSourceFailures.many": "{count} джерел повернули помилку",
    "partialSourceFailures.one": "{count} джерело повернуло помилку",
    "pause": "Пауза",
    "pauseDownload": "Призупинити завантаження",
    "paused": "Призупинено",
    "peopleAndOthers": "{names} та ін.",
    "play": "Слухати",
    "playback": "Відтворення",
    "playbackSource": "Джерело",
    "playbackSpeed": "Швидкість відтворення",
    "player": "Програвач",
    "playerSettingsHint": "Швидкість, таймер сну та керування розділами розташовані в повному програвачі.",
    "previewButtons": "Кнопки",
    "previewCards": "Картки",
    "previewChips": "Чипи",
    "previewInputs": "Поля введення",
    "previewStates": "Стани",
    "previousChapter": "Попередній розділ",
    "previousTabs": "Попередні вкладки",
    "projectWebsite": "Сайт проєкту",
    "proxy": "Проксі",
    "queued": "У черзі",
    "queuedDownloads": "Черга",
    "ratingOutOfFive": "{rating} із 5",
    "realSourceHomeMessage": "Пошук, картки, розділи, програвач і завантаження підключені до джерел Izib, Akniga, Yakniga, Knigavuhe, Knigoblud і Baza Knig.",
    "realSourceHomeTitle": "Знайдіть книгу",
    "recentSearches": "Історія пошуку",
    "recommended": "Рекомендації на тестових даних",
    "removeFavorite": "Прибрати з улюбленого",
    "removeFromLater": "Прибрати з «Пізніше»",
    "resume": "Продовжити",
    "resumeDownload": "Продовжити завантаження",
    "retry": "Повторити",
    "rewind15": "Назад на 15 секунд",
    "saveBookmark": "Зберегти закладку",
    "savedBookMediaUnavailable": "Немає збережених аудіорозділів. Знайдіть книгу в джерелі.",
    "savedBookNotFound": "Книгу не знайдено в бібліотеці",
    "savedBookPlaybackError": "Не вдалося почати відтворення",
    "search": "Пошук",
    "searchByAuthor": "Автор",
    "searchByGenre": "Жанр",
    "searchByNarrator": "Читець",
    "searchBySeries": "Цикл",
    "searchByTitle": "Назва",
    "searchHint": "Назва, автор, читець, цикл або жанр",
    "searchHistoryEmptyMessage": "Тут з’являться ваші нещодавні запити — їх можна повторити або видалити.",
    "searchReadyMessage": "Пошук підключений до джерел Izib, Akniga, Yakniga, Knigavuhe, Knigoblud і Baza Knig.",
    "searchReadyTitle": "Введіть запит",
    "searchResults": "Результати",
    "searchScope": "Шукати за",
    "searchShortQueryMessage": "Введіть щонайменше 2 символи.",
    "searchShortQueryTitle": "Запит закороткий",
    "searchingSources": "Пошук у джерелах...",
    "selectAtLeastOneSearchKind": "Виберіть хоча б одне поле пошуку.",
    "selectAtLeastOneSource": "Виберіть хоча б одне джерело",
    "selectedSourcesCount.few": "{count} джерела увімкнено",
    "selectedSourcesCount.many": "{count} джерел увімкнено",
    "selectedSourcesCount.one": "{count} джерело увімкнено",
    "series": "Цикл",
    "settings": "Налаштування",
    "settingsApplication": "Застосунок",
    "settingsContent": "Вміст і сховище",
    "settingsPersonalization": "Персоналізація",
    "settingsSections": "Розділи налаштувань",
    "share": "Поділитися",
    "shareLinkCopied": "Посилання скопійовано",
    "shareSlovofonLink": "Посилання Slovofon",
    "shareSourceLink": "Посилання джерела",
    "showFullDescription": "Показати повністю",
    "showMoreChapters.few": "Показати ще {count} розділи",
    "showMoreChapters.many": "Показати ще {count} розділів",
    "showMoreChapters.one": "Показати ще {count} розділ",
    "showPercentOnCovers": "Відсоток прослуховування на обкладинках",
    "showSourceOnCards": "Назва джерела на картках",
    "skipUpdate": "Пропустити версію",
    "sleepTimer": "Таймер сну",
    "sleepTimerUntilChapterEnd": "До кінця розділу",
    "snackbarPreview": "Спливне повідомлення",
    "sort": "Сортування",
    "sortByDuration": "тривалість",
    "sortByRating": "рейтинг",
    "sortByRelevance": "релевантність",
    "sortByTitle": "назва",
    "sortByYear": "рік",
    "sourceDisplayName.akniga": "Akniga",
    "sourceDisplayName.bazaKnig": "Baza Knig",
    "sourceDisplayName.izib": "Izib",
    "sourceDisplayName.knigavuhe": "Knigavuhe",
    "sourceDisplayName.knigoblud": "Knigoblud",
    "sourceDisplayName.yakniga": "Yakniga",
    "sourceDownloadDisabled": "Завантаження з цього джерела вимкнено в налаштуваннях",
    "sourceFilter": "Джерела",
    "sourcePage": "Сторінка на сайті джерела",
    "sourcePageOpenError": "Не вдалося відкрити сторінку джерела",
    "sourceResultsCount.few": "{count} результати",
    "sourceResultsCount.many": "{count} результатів",
    "sourceResultsCount.one": "{count} результат",
    "sourceSearchDisabled": "Виключено з пошуку",
    "sourceSearchEnabled": "Включено до пошуку",
    "sourceSearchError": "Не вдалося виконати пошук",
    "sourceStats": "Статистика джерела",
    "sourceStreamingDisabled": "Відтворення з цього джерела вимкнено в налаштуваннях",
    "sourceUnavailableMessage": "Повторіть спробу пізніше або перевірте з’єднання.",
    "sourceUnavailableTitle": "Джерело «{sourceName}» недоступне",
    "sources": "Джерела",
    "startedBooks": "Розпочаті книги",
    "subscription": "Підписка",
    "success": "Успішно",
    "systemLanguage": "Мова системи",
    "telegramChannel": "Telegram-канал",
    "telegramChat": "Telegram-чат",
    "telegramSupportBot": "Telegram-бот підтримки",
    "terabyteUnit": "ТБ",
    "textSize": "Розмір тексту",
    "textSizeHint": "100% — системний розмір тексту. Зміни застосовуються після відпускання повзунка.",
    "textSizeLabel": "Розмір тексту: {percent}%",
    "textSizePreview": "Так виглядатиме текст у застосунку.",
    "textSizeReset": "Повернути 100%",
    "theme": "Тема",
    "themeAmoled": "AMOLED",
    "themeDark": "Темна",
    "themeLight": "Світла",
    "themeModeLabel": "Тема: {value}",
    "themePreview": "Попередній перегляд теми",
    "themeSystem": "Системна",
    "unknown": "Невідомо",
    "unknownSize": "Розмір невідомий",
    "updateAvailableMessage": "Доступна версія {version}. Розмір оновлення: {size}.",
    "updateAvailableTitle": "Доступне оновлення",
    "updateChannel": "Канал оновлень",
    "updateCheckFailed": "Не вдалося перевірити оновлення",
    "updateCheckFailedMessage": "Перевірте з’єднання та натисніть «Повторити».",
    "updateDownloadFailed": "Не вдалося завантажити оновлення",
    "updateDownloadFailedMessage": "Перевірте з’єднання та натисніть «Повторити».",
    "updateDownloadProgress": "{downloaded} із {total} · {speed}/с",
    "updateDownloadZip": "Завантажити ZIP",
    "updateDownloading": "Оновлення завантажується...",
    "updateInstallFailed": "Не вдалося запустити оновлення",
    "updateInstallFailedMessage": "Не вдалося підготувати або відкрити файл оновлення. Перевірте дозволи системи та натисніть «Повторити». Застосунок не буде закрито автоматично.",
    "updateInstallPermissionRequired": "Дозвольте встановлення APK для Slovofon і натисніть «Оновити» ще раз.",
    "updateInstallerHint": "Після перевірки файлу відкриється інсталятор. Дотримуйтеся його вказівок; налаштування, прогрес і завантажені книги збережуться.",
    "updateInstallerStarted": "Інсталятор оновлення відкрито",
    "updateLater": "Пізніше",
    "updateManualDownloadHint": "Не вдалося надійно визначити тип встановлення Windows. Виберіть відповідний файл на сторінці випусків; застосунок не буде замінено автоматично.",
    "updateNotesAlert.caution": "Увага",
    "updateNotesAlert.important": "Важливо",
    "updateNotesAlert.note": "Примітка",
    "updateNotesAlert.tip": "Порада",
    "updateNotesAlert.warning": "Попередження",
    "updateNotesLinkFailed": "Не вдалося відкрити посилання. Перевірте, чи встановлено браузер.",
    "updateNotesRemoteHint": "Угору й униз — прокручування. Праворуч — перехід до посилань.",
    "updateNotesTruncated": "Показано частину опису. Повний текст доступний на сторінці випуску.",
    "updateNow": "Оновити",
    "updateOpenReleases": "Відкрити сторінку випусків",
    "updatePortableHint": "ZIP-архів буде завантажено й перевірено. Потім закрийте Slovofon і розпакуйте архів у нову теку. Не видаляйте теки з даними користувача та завантаженими книгами.",
    "updatePortableReady": "Архів перевірено; відкрито теку завантаження. Закрийте Slovofon і розпакуйте ZIP у нову теку.",
    "updatePreparingTitle": "Перевірка та запуск оновлення",
    "updateReleaseNotes": "Що нового",
    "updateReleasePageFailed": "Не вдалося відкрити сторінку випусків. Повторіть спробу.",
    "updateSkipFailed": "Не вдалося зберегти пропуск версії. Повторіть спробу або натисніть «Пізніше».",
    "updateUnsupportedPlatform": "Для цієї платформи немає відповідного файлу оновлення",
    "volume": "Гучність",
    "warning": "Увага",
  },
};
